### ISSUE TITLE
Defining preprocessor variables within procedures

### ISSUE THREAD

**Issue by jodavies** [vermaseren/form#102]
Is it intended that preprocessor variables lose their definition after returning? For example,
```
#procedure dodefine(ARG)
	#define TEST "`ARG'"
#endprocedure

#call dodefine(1)
#message TEST = `TEST'

.end
```
gives `Line 6 ==> Undefined preprocessor variable TEST`.

I don't know if this is something that has changed over the years? The safeguards against re-declaration of the htables in harmpol.h (the definition of HTABLEnFILL) are ineffectual if you call htables more than once (which is how I came across this).

Thanks,
Josh.

**Comment by vermaseren** [comment]
It has always been like this and it is intended.
It is described in the courses that you can find in the FORM pages.
The preprocessor variables go on a stack. So do the arguments in the procedure call.
FORM looks for a variable starting at the top of the stack. This way you can have ‘local’ definitions.
If you want to keep the value you should define the object in the calling routine and use #redefine
inside the procedure.
Alternatively you could use dollar variables. They would keep their value once defined.

Jos

**Comment by jodavies** [comment]
OK thanks, just checking.

I will guard against redeclaration within my own procedure.
