### ISSUE TITLE
Cross-compiling 32-bit FORM on a 64-bit Linux host fails

### ISSUE THREAD

**Issue by vsht** [vermaseren/form#109]
Hi,

I'm using Fedora 23 64-bit and when I try to cross-compile 32-bit version of FORM (latest commit from master) with "--disable-native" and "--enable-static-link", the compilation fails because of "static_assertion_failed_232" being negative. 

This is how I compile
```
sudo dnf install libstdc++-static glibc-static glibc-devel.i686
git clean -f
./configure --host=i686-pc-linux --disable-native --enable-static-link
make clean
make
```
The full console output is here:

http://pastebin.com/aPCWnWVX

Is this a known problem, or am I doing something wrong?

Cheers,
Vladyslav

**Comment by tueda** [comment]
Hi, personally I haven't tried for cross-compiling, so I'm not sure if it works. But in your build log, cross-compiling seemed to fail to find cross compilers:
```
checking for i686-pc-linux-gcc... no
```
```
checking whether we are cross compiling... no
```
```
checking for i686-pc-linux-g++... no
```
I don't know whether or not Fedora provides packages for cross-compiling.

Another strange thing in your build log is that somehow `-m32` option was used for `gcc`, but not used for `g++`. It looks like the configuration was done for 32-bit system (ILP32), so compiling the C++ sources led to inconsistency of data model. If you just want to build a 32-bit binary of FORM that runs on your system, I guess
```
./configure CFLAGS=-m32 CXXFLAGS=m32
```
may work (if your system has multilib support).

**Comment by vsht** [comment]
Thanks a lot for the correct `CFLAGS`, at the end the following compiled fine

```
sudo dnf install libstdc++-static.i686 glibc-static.i686 glibc-devel.i686 libstdc++-devel.i686 glibc-*.i686 gcc-c++.i686
./configure CFLAGS=-m32 CXXFLAGS=-m32 --disable-native --enable-static-link
make clean
make -j4
```
