### ISSUE TITLE
Form compiler allows lone ? on rhs

### ISSUE THREAD

**Issue by benruijl** [vermaseren/form#125]
This compiles (and crashes), but shouldn't:

	#-
	CF f;

	L F = f;
	id f = f(?);

	.end

**Comment by tueda** [comment]
Fixed in c11ae7c634. Note that the following construct is valid:
```
V p;
I mu;
CF f;
L F = p(mu);
id p = f(?);
P;
.end
```
```
   F =
      f(mu);
```
