### ISSUE TITLE
Pattern with index and set restriction matches to number 

### ISSUE THREAD

**Issue by benruijl** [vermaseren/form#153]
The following `id` statement matches even though it shouldn't:

````
#-
I mu1,mu2,mu3;
CF f;
Set indices:mu1,mu2,mu3;

L F = f(132); * only happens for certain numbers!
id f(mu1?indices) = 1; * matches...

Print +s;
.end
````

**Comment by tueda** [comment]
As you may imagine
```
On code;
I mu1,mu2,mu3;
.end
```
prints
```
 Indices
   iarg_(129) mu1(130) mu2(131) mu3(132)
```

**Comment by tueda** [comment]
A (silly) workaround is putting
```
#:constindex 10000
```

**Comment by tueda** [comment]
To me, the problem (also in #149) is resolved if we forbid a small number function argument that is not in the range of fixed indices matching with any indices at [function.c:1242](https://github.com/vermaseren/form/blob/6fe5632f513100fcabdc4c7fb002609b1bf8efea/sources/function.c#L1242):
```
diff --git a/sources/function.c b/sources/function.c
index 7ec75dd..87fc8f0 100644
--- a/sources/function.c
+++ b/sources/function.c
@@ -1239,7 +1239,8 @@ IndAll:                           i = m[1] - WILDOFFSET;
                        else if ( *m == -ARGWILD ) goto ArgAll;
                        else if ( *m == -INDEX && m[1] >= AM.OffsetIndex+WILDOFFSET
                        && m[1] < AM.OffsetIndex+(WILDOFFSET<<1) ) {
-                               if ( *t == -VECTOR || *t == -SNUMBER ) goto IndAll;
+                               if ( *t == -VECTOR ) goto IndAll;
+                               if ( *t == -SNUMBER && t[1] >= 0 && t[1] < AM.OffsetIndex ) goto IndAll;
                                if ( *t == -MINVECTOR ) {
                                        i = m[1] - WILDOFFSET;
                                        AN.argaddress = AT.MinVecArg;
```
Am I right? I'm still not sure about the fixed indices...

**Comment by vermaseren** [comment]
Hi Takahiro,

That sounds about right. It is probably just a simple if somewhere in the code.
I am a bit too busy with the colors at the moment. There is a nontrivial bug, either in color.h or in FORM.
This is far more serious.

Jos

**Comment by tueda** [comment]
Hi Jos,

OK. I will commit this patch, which fixes at least these cases.
We will see if there are more related bugs.

**Comment by benruijl** [comment]
Sadly, the patch does not work for symmetric functions yet:

````
#-
Index mu1,mu3;
CF f(s);
L F = f(-1,-1);

id f(mu1?,mu3?) = mu3;

Print +s;
.end
```
