### ISSUE TITLE
gcc-7

### ISSUE THREAD

**Issue by alexmyczko** [vermaseren/form#181]
if you can say anything about this bug, that'd be great:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=853404

**Comment by tueda** [comment]
According to the full build log, the configure script failed in the check for `mpic++`:
> configure:6446: mpic++ -o conftest -g -O2 -fdebug-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -Wl,-z,relro -Wl,-z,now conftest.cpp  >&5
In file included from /usr/include/mpich/mpi.h:2231:0,
                 from conftest.cpp:42:
/usr/include/mpich/mpicxx.h:21:4: error: #error 'Please use the same version of GCC and g++ for compiling MPICH and user MPI programs'

> configure:6538: error: test for parform failed. Give --disable-parform if you do not need to build parform

It sounds like a version mismatch of gcc-7 with the packaged MPICH.

**Comment by alexmyczko** [comment]
Sorry about that, I'll forward your reply then to the BTS of Debian...
