### ISSUE TITLE
$args not expanded for distrib_

### ISSUE THREAD

**Issue by tueda** [vermaseren/form#186]
Argument fields seem not to be expanded when `distrib_` functions are evaluated:
```
S x1,...,x4;
CF f;
L F = f(x1,...,x4);
id f(?a$a) = 1;
multiply distrib_(1,1,f,dummy_,$a);
P;
.end
```
gives
```
   F =
      f(x1,x2,x3,x4);
```

Workaround:
```
S x1,...,x4;
CF f;
CF distrib;
L F = f(x1,...,x4);
id f(?a$a) = 1;
multiply distrib(1,1,f,dummy_,$a) * replace_(distrib,distrib_);
P;
.end
```
```
   F =
      f(x1) + f(x2) + f(x3) + f(x4);
```

**Comment by vermaseren** [comment]
Probably, in TestSub, the distrib_ function gets intercepted while there are still dollars
in the arguments. That should be vetoed. After that things should(!) be fine.

Jos
