### ISSUE TITLE
Registration on forum

### ISSUE THREAD

**Issue by FeelUsM** [vermaseren/form#193]
Hello

How long time needed my account to be activated?
I have registered on 7th March.
username - FeelUs
Also I tried to registr with other email on 23 May, username FeelUs1.
But both my accounts have not been activated yet.

Thanks,
Philipp

**Comment by tueda** [comment]
As [REDAME](https://github.com/vermaseren/form/blob/954024f163e8d702e1f28c1dd99846c08b0333f8/README.md) says, the FORM forum will be discontinued in the future for maintenance reasons.
