### ISSUE TITLE
Sorting terms with different indix names

### ISSUE THREAD

**Issue by FeelUsM** [vermaseren/form#195]
I often have expressions like A(mu,nu)*B(mu,nu)+A(nu,mu)*B(nu,mu).
How to tell form that this is the same term, and how to do form to add this terms?

I ask my question here because my account on forum has not been activated yet.

Thanks,
Philipp

**Comment by vermaseren** [comment]
You can look at the sum statement.
You should issue the command
sum mu,nu;

Jos

**Comment by tueda** [comment]
A concrete example:
```
I mu,nu;
CF A,B;
L F = A(mu,nu)*B(mu,nu)+A(nu,mu)*B(nu,mu);
P;
.sort
Sum mu,nu;
P;
.end
```
```
FORM 4.1 (Jun  8 2017, v4.1-20131025-351-g31c5798) 64-bits  Run: Thu Jun  8 20:26:08 2017

   F =
      A(mu,nu)*B(mu,nu) + A(nu,mu)*B(nu,mu);

   F =
      2*A(N1_?,N2_?)*B(N1_?,N2_?);
```
