### ISSUE TITLE
Add release notes for 4.2

### ISSUE THREAD

**Issue by benruijl** [vermaseren/form#204]

**Comment by tueda** [comment]
Here is a "raw" change log: https://gist.github.com/tueda/001995ac1db6c2135ee61458f3b75114.

**Comment by tueda** [comment]
Some progress: https://gist.github.com/tueda/001995ac1db6c2135ee61458f3b75114#file-changelog-md.

**Comment by benruijl** [comment]
Added an example for O4 to the release notes:
https://gist.github.com/benruijl/9491c567caf1140730a5c37e7b3bbdee#file-changelog-md

**Comment by tueda** [comment]
Can you put/merge https://gist.github.com/tueda/0d301b39512358e5744f199bbb7ba787#file-releasenote-changes-md in the release notes? Then we can remove the ChangeLog file.

**Comment by benruijl** [comment]
The release notes are done: https://gist.github.com/benruijl/9491c567caf1140730a5c37e7b3bbdee#file-changelog-md

**Comment by benruijl** [comment]
It's released!

**Comment by vermaseren** [comment]
Congratulations and thanks for the hard work.

Jos

**Comment by jodavies** [comment]
I'd also like to thank you all for the hard work! Having the development process open on github, and your fast responses to questions, bug reports, feature requests etc makes it very nice software to use.

Thanks a lot!
Josh.
