### ISSUE TITLE
Add undocumented features to documentation

### ISSUE THREAD

**Issue by benruijl** [vermaseren/form#209]
- `tempsortdir` setup parameter, `$TEMPSORTDIR` environment variable and
  `-ts` command line option
- `#AppendPath` and `#PrependPath`
- `mul_`
  ([#49](https://github.com/vermaseren/form/pull/49))
- `partitions_`
- `optimvalue_`, `optimscheme_`

**Comment by tueda** [comment]
I will write documents for `#AppendPath`, `#PrependPath` and `mul_`.

**Comment by benruijl** [comment]
I have added documentation for `partitions_`, `optimvalue_`, and `optimscheme_`.
