### ISSUE TITLE
Corrupted characters in {-9223372036854775808}

### ISSUE THREAD

**Issue by tueda** [vermaseren/form#219]
The preprocessor calculator prints the minimum negative number wrongly.
```
* for 64-bits version
#message {-9223372036854775808}
.end
```
```
FORM 4.2.0 (Jul 11 2017, v4.2.0-8-ga8b9963) 64-bits  Run: Wed Jul 12 14:22:11 2017

~~~-(
```
Presumably for the same reason as in #139.

**Comment by tueda** [comment]
Failed with `clang`?? https://travis-ci.org/tueda/form/builds/253705758 (See `Issue219`.)

**Comment by vermaseren** [comment]
I am not quite sure what you mean with this.
On the apple my fix worked.

Jos

**Comment by tueda** [comment]
It seems that the following code gave an error with `clang` in macOS on Travis CI:
```	
#$n64  = -2^63;
L F64  = {`$n64'};
P;
.end
```

**Comment by tueda** [comment]
You need to turn on the optimization. Probably something hits on an undefined behaviour, which compilers are allowed to discard smartly. In the following link you can play "Run" with/without "Optimization": https://wandbox.org/permlink/Bhe1uTtaJ4niW9Z5

**Comment by tueda** [comment]
I guess
```
if ( answer < 0 ) { answer = -answer; }
```
is already undefined for `answer=-9223372036854775808` (overflow in signed arithmetic). See https://godbolt.org/g/oX98bo, in which gcc completely skips a conditional branch with `-O1`.
