### ISSUE TITLE
building reference manual doc

### ISSUE THREAD

**Issue by alexmyczko** [vermaseren/form#232]
fails for me with the last lines being:

Underfull \hbox (badness 10000) detected at line 299
[][][]
[339] [340] [341] [342] [343]) (./wildcard_8c.tex
Underfull \hbox (badness 10000) in paragraph at lines 3--4

) [344] (./doxygen.ind [345] [346] [347] [348] [349] [350] [351] [352] [353]
[354] [355] [356] [357] [358] [359] [360])

Package longtable Warning: Table widths have changed. Rerun LaTeX.

(./doxygen.aux)

Package rerunfilecheck Warning: File `doxygen.out' has changed.
(rerunfilecheck)                Rerun to get outlines right
(rerunfilecheck)                or use package `bookmark'.

LaTeX Warning: There were undefined references.

 )
(see the transcript file for additional information){/usr/share/texlive/texmf-d
ist/fonts/enc/dvips/base/8r.enc}</usr/share/texlive/texmf-dist/fonts/type1/publ
ic/amsfonts/cm/cmmi10.pfb></usr/share/texlive/texmf-dist/fonts/type1/public/ams
fonts/cm/cmmi7.pfb></usr/share/texlive/texmf-dist/fonts/type1/public/amsfonts/c
m/cmsy10.pfb></usr/share/texlive/texmf-dist/fonts/type1/public/amsfonts/cm/cmsy
7.pfb></usr/share/texlive/texmf-dist/fonts/type1/public/amsfonts/cm/cmsy8.pfb><
/usr/share/texlive/texmf-dist/fonts/type1/urw/courier/ucrr8a.pfb></usr/share/te
xlive/texmf-dist/fonts/type1/urw/courier/ucrro8a.pfb></usr/share/texlive/texmf-
dist/fonts/type1/urw/helvetic/uhvb8a.pfb></usr/share/texlive/texmf-dist/fonts/t
ype1/urw/helvetic/uhvb8ac.pfb></usr/share/texlive/texmf-dist/fonts/type1/urw/he
lvetic/uhvr8a.pfb></usr/share/texlive/texmf-dist/fonts/type1/urw/helvetic/uhvro
8a.pfb>
Output written on doxygen.pdf (394 pages, 1191796 bytes).
Transcript written on doxygen.log.
cp pdflatex/doxygen.pdf doxygen.pdf
make[3]: Leaving directory '/home/sengun/public_html/debian/form/form-4.2.0+git20170914/doc/doxygen'
Making pdf in manual
make[3]: Entering directory '/home/sengun/public_html/debian/form/form-4.2.0+git20170914/doc/manual'
[ -f version.tex ] || ln -s "./version.tex.in" version.tex
/usr/bin/pdflatex manual.tex; while [ `grep -v 'Package: rerunfilecheck' manual.log | grep -c Rerun` -gt 0 ]; do /usr/bin/pdflatex manual.tex; done
This is pdfTeX, Version 3.14159265-2.6-1.40.17 (TeX Live 2016/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./manual.tex
LaTeX2e <2017/01/01> patch level 3
Babel <3.9r> and hyphenation patterns for 10 language(s) loaded.
(./version.tex
! Missing control sequence inserted.
<inserted text>
                \inaccessible
l.2 e
     pomajorversion{4}

full build log available at: https://people.phys.ethz.ch/~myczko/debian/form/form_4.2.0+git20170914-1_amd64.build

any hint & help is welcome. this happens on debian.

**Comment by tueda** [comment]
This is not at building the doxygen document, but at building the reference manual. Can you show `version.tex` in `doc/manual`? The error
```
(./version.tex
! Missing control sequence inserted.
<inserted text> 
                \inaccessible 
l.2 e
     pomajorversion{4}
? 
```
is very strange. Somehow LaTeX failed to parse
```
\def\repomajorversion{4}
```

The log says you are not in a proper git repository:
```
fatal: Not a git repository (or any parent up to mount point /home/sengun)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
========================================================================
Failed to determine the revision of the source code.
```
and it goes to a fallback mode. Maybe this would be a problem to build the document, but I'm not sure for now.

**Comment by alexmyczko** [comment]
since i wasn't able to build the 4.2.0 release tarball, i took a gitcheckout that's version 4.2.0+git20170914. the version.tex says:

\def
epomajorversion{4}
\def
epominorversion{2}

**Comment by tueda** [comment]
Sounds like somehow `\r` was replaced with a carriage-return...

**Comment by tueda** [comment]
Can you try the patch https://github.com/tueda/form/commit/8dfb0aa50049266b2603bcde52ca8ce5b848edc6 on the [`build-dash` branch of `tueda/form`](https://github.com/tueda/form/tree/build-dash)? It should work without the git repository.

(But still probably better to build it from a proper git repository with the `.git` directory.)

**Comment by alexmyczko** [comment]
Your patch works for me. Many thanks.

**Comment by tueda** [comment]
OK. I will merge this patch after resolving some Travis CI issues.
