### ISSUE TITLE
Print statements do nothing when there are no active expressions

### ISSUE THREAD

**Issue by jodavies** [vermaseren/form#239]
The following program prints nothing:
```
#-
*Local test = 1;
Print "hello";
.end
```
If one uncomments the expression, FORM prints `hello` as I would expect.

Similarly, this also prints nothing:
```
#-
Local test = 1;
.sort
Hide test;
Print "hello";
.end
```

Thanks,
Josh

**Comment by benruijl** [comment]
The `print` statement is executed for every expression, so if there are none, nothing happens.

You could use `#write` instead.

**Comment by tueda** [comment]
It is a bit tricky point that `Print` has two meanings (1) print terms and (2) print expressions at the end of the module.

**Comment by jodavies** [comment]
Ah, yes, of course. Usually I use #message for such things, but for some reason I was using a print like this somewhere, and it took me a while to track down why nothing was happening... Thanks!
