### ISSUE TITLE
Beginner Q: is it possible to have 2 sets of indices with 2 different ranges?

### ISSUE THREAD

**Issue by fetchinson** [vermaseren/form#256]
I'd like to use FORM for summing over and manipulating spacetime indices as well as summing over and manipulating color indices (more generally going from 1 to N). Is it possible? For instance if I have a propagator like $G(\mu,\nu,a,b) = \delta_{\mu\nu} / k^2 \delta_{a, b}$ then I'd like to be able to do the double trace $G(\mu,\nu,a,b) G(\mu,\nu,a,b) = DN/k^4$ (obviously in actual examples the expressions would be more complicated). How do I specify that one type of index has range 0...(D-1) and the other 1...N? (The latter can also be 0...(N-1) of course, that's no problem.)

**Comment by vermaseren** [comment]
You can handle this in the declaration of the indices.
In your case
Symbol D,N;
Index mu=D,nu=D,a=N,b=N;
should do the trick. It causes d_(mu,mu) to be replaced by D and d_(a,a) by N.
Hence your d_(mu,nu)*d_(mu,nu) will become D as well. Etc.

I hope this is what you are after.

Jos

**Comment by fetchinson** [comment]
Yes, thank you very much, exactly what I needed.
