### ISSUE TITLE
Beginner Q: how to define partially (anti)symmetric tensors

### ISSUE THREAD

**Issue by fetchinson** [vermaseren/form#257]
If I have a tensor, T(a,b,c), which is (anti)symmetric in the first two indices but we don't know anything about the last index then is there a way to specify this for FORM? What I tried is

Tensor T;
* symmetric case
id T(a?,b?,c?) = T(a,c,b);
* antisymmetric case
id T(a?,b?,c?) = -T(a,c,b);

which seems to work but I'm not sure if this is optimal or recommended. In more complicated cases like a 4-index tensor, T(a,b,c,d), which has lots of symmetry properties but is not completely symmetric or anti-symmetric I need to specify lots of "id" statements which may not be the best solution.

What would be the recommended way of doing this?

**Comment by tueda** [comment]
I think you can use the [`symmetrize`](https://www.nikhef.nl/~form/maindir/documentation/reference/online/online.html#substasymmetrize) command (and [`antisymmetrize`](https://www.nikhef.nl/~form/maindir/documentation/reference/online/online.html#substaantisymmetrize)) for partially (anti)symmetric tensors:
```
T t;
I a,b,c,d;
L F = t(d,c,b,a);
symmetrize t:4 1,2,3;  * symmetric for the first 3 indices out of 4 indices
P;
.end
```
```
   F =
      t(b,c,d,a);
```
