### ISSUE TITLE
Version 4.2.1?

### ISSUE THREAD

**Issue by tueda** [vermaseren/form#263]
More than a half year has passed after the release of version 4.2.0. Maybe it would be good to start to consider a possible next version slowly.

Questions are:
1. Do we need a bug-fix release 4.2.1? Or wait for 4.3?
2. For 4.2.1, should more fixes and some small additions be included? Which ones?

The current changes are summarized in https://github.com/vermaseren/form/wiki/Recent-ChangeLog, if I don't miss anything. It includes annoying gzip bugs and polynomial GCD bugs.

Ubuntu 18.04 LTS (Bionic Beaver) will appear on [26 April 2018](https://wiki.ubuntu.com/BionicBeaver/ReleaseSchedule) (and will be supported until April 2023), may be shipped with the `FORM 4.2 (Sep 14 2017)`  anyway: https://packages.ubuntu.com/bionic/form.
(They dropped `.0` of `4.2.0` from `form -v`.)

**Comment by jodavies** [comment]
If a version 4.2.1 is released, it could be useful to provide a `SUBSUBVERSION_` preprocessor variable. One could use this to enforce a certain level of bug-fixing in a script.

**Comment by alexmyczko** [comment]
Early 2019, Debian will ship a new stable release, maybe it'd be great to have a new release short before of that for them to deliver?

**Comment by benruijl** [comment]
That sounds like a good idea!

**Comment by tueda** [comment]
I think even the current one (+ possibly some bugfixes + extra) would be OK for 4.2.1 or 4.3.0, once Jos is satisfied with the version. Here is the changes from 4.2: https://github.com/vermaseren/form/wiki/Recent-ChangeLog.

**Comment by vermaseren** [comment]
Would a date in early Januari be fine, or is there more of a hurry.
Potentially we might get in the namespaces in that case.
Some of the outstanding bugfixes are rather hard, but I can try.

Version 4.3.0 would be fine. Specially if we get the namespaces.

Jos

**Comment by alexmyczko** [comment]
Summary from https://release.debian.org/buster/freeze_policy.html
2019-01-12 - Transition freeze
2019-02-12 - Soft-freeze
2019-03-12 - Full-freeze

I'd go for earlier so some people can already test it, it takes 5 days from unstable to wander into testing (which will become stable after the freeze)

**Comment by alexmyczko** [comment]
any news here? happy new year!

**Comment by benruijl** [comment]
Form 4.2.1 has been released!

**Comment by tueda** [comment]
You failed. The build script can't recognize the version because it must be `v4.2.1`; I think the configure script still says `FORM 4.2.0` in your build (you need to rerun `autoreconf -ifv`).  See:
https://github.com/vermaseren/form/blob/eaf85a757a9f7bb69c9bdc4bf6ec07e48f5769ac/scripts/git-version-gen.sh#L99-L103
Another problem was the Github token to deploy files to the release page was somehow expired(?) I don't remember whose token was used, but for now I put my token. Can you put the correct tag and remake the release?

Maybe copyrights should be updated (to 2019), but this is a minor release and we may skip it...

**Comment by tueda** [comment]
By the way, why do you spell `Form` instead of `FORM` while you spell `reFORM` for your software :-)

**Comment by benruijl** [comment]
Ah yes, you are totally right. I should push a version bump and then move the tag. I can do that tomorrow.

**Comment by tueda** [comment]
Thanks! Now the tarball gives
```
FORM 4.2.1 (Nov 21 2018, v4.2.1) 64-bits         Run: Mon Feb  4 21:45:30 2019
```
Ben, can you also update the AUR package? I will update the Homebrew one and the [installation page](https://github.com/vermaseren/form/wiki/Installation).

**Comment by tueda** [comment]
For undocumented changes, yes, we could just keep them in the change log, and they would be officially not supported in 4.2.1. But for the setup parameters, now the manual is wrong...

**Comment by benruijl** [comment]
Yes that is unfortunate... I don't know what the best course of action is. In the future we should document in the same commit.

**Comment by tueda** [comment]
Because different memory sizes are assigned for sequential and threaded versions in https://github.com/vermaseren/form/commit/689b72dd76f3da7b52ee0fd9bd00d325c1cc0c9b#diff-0a9454c43ec7e8c79439a330681bf16d, perhaps the table for default settings needs 4 columns? Or the whole layout of the table should be reconsidered? ....Hopefully will be fixed in v4.2.1.1 or something like that.

**Comment by alexmyczko** [comment]
where's the new tarball? checkout master and call it 4.2.1.1?

**Comment by tueda** [comment]
The tarball of v4.2.1 is in the Github Release page: [form-4.2.1.tar.gz](https://github.com/vermaseren/form/releases/download/v4.2.1/form-4.2.1.tar.gz). A possible next version v4.2.1.1 (or v4.3.0) is still a science fiction.

**Comment by tueda** [comment]
@alexmyczko Could you show the log of `./configure` and `make pdf`, for example, by putting the log in a Gist?

**Comment by alexmyczko** [comment]
I don't know what gist is, nor do i have it. But I have this log file: http://phd-sid.ethz.ch/debian/form/form_4.2.1-1_amd64.build

**Comment by tueda** [comment]
Probably you have a file `form/doc/doxygen/pdflatex/comtool_8c.tex` generated by Doxygen. Can you paste the first 100 lines? The error occurred around l.73.

**Comment by alexmyczko** [comment]
can you browse the url it should be all there see debian/rules i inly want the pdf for the 100 lines should also be there...

**Comment by tueda** [comment]
OK, I can see the `comtool_8c.tex`, but I don't see anything clearly wrong around l.73....

**Comment by tueda** [comment]
As far as I understand, you only install `doc/manual/manual.pdf` (in `form-docs.docs`), so
```
override_dh_auto_build:
	dh_auto_build
	$(MAKE) -C doc/manual pdf
```
would be enough, I guess.
