### ISSUE TITLE
stdin as the input file?

### ISSUE THREAD

**Issue by tueda** [vermaseren/form#264]
Suppose one wants to run some FORM program that is dynamically created in a shell script or some program. Then one has to make a temporary file for the FORM input. The file name should be unique and the file must be guaranteed to be deleted after finishing the calculation while FORM needs to access to it by the file name (i.e., `unlink` before `close` doesn't work). This is a bit cumbersome and one is forced to handle
1. making a unique file name for a temporary file (or fifo) in a secure way,
2. signal handling for deleting the file; deleted even when `Ctrl+C` is pressed.

`mkstemp` to generate a unique name `tmpXXXXXX` or  process-private pipes for  `/dev/fd/<n>` are useless because FORM doesn't accept file names without `.frm`. Signal handlers are basically global, so a pain in the neck for OOP.

So I was just wondering why FORM doesn't support input passed via the standard input, which makes such temporary files unnecessary. It would be nice if the following could work:
```shell
cat <<END | form -q -i
Off stats;
S x;
L F = (1+x)^2;
P;
.end
END
```
Here I have assumed `-i` indicates FORM reads input from the standard input (though I know it is reserved for "interactive" session). The option may be other forms, e.g., `-in`, or we could make a special file name `-` (as `form -`) that means the standard input.

**Comment by tueda** [comment]
What would be wrong if FORM accepts input file names without `.frm`?

As I wrote above, FORM rejects when I pass the file name `/dev/fd/5` and says `/dev/fd/5.frm` doesn't exist, even if `/dev/fd/5` certainly exists and `/dev/fd/5.frm` never exists. Another example is a script as an executable. The following script
```
#-!bin/sh
#- \
exec form -q "$0"
L F = 1;
P;
.end
```
can be executable if it is named as `foo.frm` with `chmod +x foo.frm`. But it doesn't work if I rename it to `foo`.

**Comment by vermaseren** [comment]
A couple of remarks.
Form scans the input file for instructions that may refer to a setup.
Then it rewinds the input and after allocations have been made, it really starts.
This makes stdin rather tricky.
Version one and two did not need the .frm extension. It made things at times rather
chaotic. Hence at a certain moment it was decided that the extension .frm would
be mandatory. It is possible to make an option in the command tail that tells that
the file does not have the extension, just for very special use.
Note that the C compiler also insists on the extension .c etc.

I think it is good that there are conventions. And whatever convention one
chooses, there will always be cases in which they may not be optimal.

Jos

**Comment by tueda** [comment]
OK. So the beginning of the input file is read for the setup before the whole contents are loaded into a buffer. I thought FORM first reads the whole input file, but that was wrong.

I agree that some file name convention is nice, though Github considers `.frm` is for Visual Basic (`.h` and `.hh` for C/C++/Objective-C and `.prc` is for SQL). The situation in C++ is rather mess such that there are `.cc`, `.cp`, `.cxx`, `.cpp`, `.CPP`, `c++` and `.C` files, but compilers can handle arbitrary suffixes by options (gcc: `-x <language>`, clang: `-x<language>`, Intel: `-x <type>`, MSVS: `/Tc` or `/Tp`).

For now, I would make temporary files starting with `.` for this purpose; they are not deleted but hidden :)

**Comment by vermaseren** [comment]
Hi Takahiro,

It reads, up to a maximum size, in one go. Rewind means going back to the
first character. But for an input stream that would
come from stdin, you would need to store everything and the logistics become
a bit more complicated as you have to dynamically extend the input. It assumes
that the ‘old’ input is still there as in a #do loop where it goes back in the input
continuously, and so on. Hence it never looked attractive to try to input from stdin.
I guess it can be done, provided you keep all input in a buffer.
There is however no possibility of ‘error correction’ when you are typing the
input.
If I am correct, there is a way to send the stuff through a pipe, but I have never
tried it.

Jos

**Comment by tueda** [comment]
> If I am correct, there is a way to send the stuff through a pipe, but I have never tried it.

I guess you are saying about `-pipe`, but the input file is still needed to start the program anyway.

**Comment by vermaseren** [comment]
Yes, but for that you could take a standard file, just to start it up. That file
would alsways be the same, and hence you could make an alias that involves
the call to that file. But you could have a look how hard it would be to input things.
You probably have to interfere a bit with the main ‘stream’ (in tools.c) and maybe
even define a new type of stream. The main problem is whether there are pointers
for this looking/winding back or whether that goes by offsets. In the first case more
things may have to be changed, because you may have to expand the input buffer
occasionally. If things go by offset, it should not be too complicated. Otherwise
much care is needed.

Jos

**Comment by tueda** [comment]
So you mean to put a hard coded startup file inside FORM. Well, I don't think there is a common startup routine. For example, https://github.com/FormLink/formlink/blob/master/src/init.frm and https://github.com/tueda/python-form/blob/master/form/init.frm are conceptually different: one-time vs. infinite loop. If one wants to change setup parameters at the beginning of the startup file, more modifications are needed (this was considered in #215).

**Comment by vermaseren** [comment]
Actually I mean that you make a file, let us assume startpipe.frm, and make a script or alias
that calls form with this file as input. But maybe I do not understand those pipes very well.

Jos

**Comment by tueda** [comment]
Well, actually what I'm trying to now is to remove such a fixed file `init.frm` or `startpipe.frm`, because I like just a one file to run some program and doesn't like an executable which always assumes that some text file is in the same directory.

**Comment by vermaseren** [comment]
I do not mean that you hard code the name into the executable of form.
what I mean is that in the shell you make an alias, let us say stdinform which is
equivalent to   form ~/formlib/startpipe   or something like that.
I also would not want such a fixed name inside the executable.

Jos

**Comment by tueda** [comment]
Maybe we are looking in opposite ways. I'm considering a possibility to make a *single* binary executable, in which a start up file is hard corded as a string. So the binary can generate a temporary `init.frm` when needed. Generating `stdinform` instead of `init.frm` is not a solution in this case; still `stdinform` has to be generated, or the binary has to assume the location of `stdinform`.

**Comment by vermaseren** [comment]
Maybe I do not understand what it is that you really want.
If you want to create things inside the executable, then you might as well
make it such that it can just deal with input redirection. Like this stream+buffer
stuff that we discussed before. Or do you want something different?

Jos

**Comment by tueda** [comment]
Even the binary does some input/output redirection or making pipes, FORM, as one of subprocesses of the binary, requires the startup file with `.frm`.

**Comment by vermaseren** [comment]
I am getting more and more confused now. I would not say that that is IO redirection or a pipe.
You can argue that the name of the form.set file is hardcoded……
Cannot you give me an example of what it is you want? (but this is my last mail for now. Tired…)

Jos

**Comment by tueda** [comment]
In short, what I'm considering is whether I can run FORM without any input or auxiliary files, and the conclusion would be "no" for now (stdin is difficult, /dev/fd/n is not allowed).

I just thought maybe nice to have a FORM version of https://github.com/mprausa/libFermat such that one can use a library to wrap FORM as a subprocess
```
main program -> library -> FORM
```
but apparently FORM is more tricky to embed than Fermat and requires a startup input file.

**Comment by vermaseren** [comment]
Would it be acceptable if you use  'form -lib' and it can find more setup info in form.set?
If this is acceptable, it will still require quite some thinking to specify how you want this
to work in a way that it can be implemented.
Just as a library to be linked in seems rather hard, because there is a whole hierarchy
of routines to go through first and many things at later stages are a bit incremental.
But I think it would be an excellent idea to make a list of requirements that such a library
needs to fulfil. Then by the time we feel that the list is more or less complete (optimist!)
we can see how that should/could be fit in. But starting too early does not look like a
good thing to me.

Jos

**Comment by tueda** [comment]
Well, if I have to use an *auxiliary* setup file `form.set`, I would prefer to use an auxiliary start up file `init.frm` because it has more flexibility (but the discussion is how to avoid `init.frm`...).

I'm mentioning a library to wrap FORM as a *subprocess* (separated process from the main process), not saying to use FORM as a library. Making FORM as a library has problems:
1. It will be very difficult to make it as a library.
2. One may want to use a part of code, if possible, but FORM is too monolithic. One cannot use a *chef's knife* but has to use a *Swiss army knife*.
3. If one uses source code of FORM or link to a FORM as a library, then the program (or library) will be not GPL-free.

**Comment by vermaseren** [comment]
If you use Form as a subprocess, you will have to have some mechanism to control the setup.
Either that or create a new executable whenever you want to change the setup.
One way  I see is with environment variables and one would have to define quite
a few new ones.
But it will have to deal with files anyway, as soon as you do something big.
Another possibility is change some order of initialization and set up the pipe first before allocations are made
for the setup, and pipe the #: setup control in that way.
Is any of this acceptable?

Jos

**Comment by tueda** [comment]
> One way I see is with environment variables and one would have to define quite a few new ones.

I'm not so sure what you mean but still a start up `.frm` file is required, right?

> But it will have to deal with files anyway, as soon as you do something big.

If one has to pass big input, it can be done via pipes.

> Another possibility is change some order of initialization and set up the pipe first before allocations are made for the setup, and pipe the #: setup control in that way.

It might be an interesting idea in general, but

1. To read something from a pipe, i.e., `#fromexternal`, the external communication routines and also the preprocessor have to be already initialized. Using the preprocessor before setup allocations is a quite big change.
2. Still FORM needs startup `.frm`. If I has to rely on a startup `.frm` file anyway, then I can put such `#:<setup>` into the startup `.frm` file.

**Comment by vermaseren** [comment]
Hence you are saying that thus far the init.frm is the best idea we have.
Would it be acceptable to have a command tail option
    form -infile=filename
where filename could be init.frm or anything else?
Or do you want to do away with the command tail as well?

Jos

**Comment by tueda** [comment]
I don't understand what is a difference between `form -infile=filename` and `form filename`...???

**Comment by vermaseren** [comment]
not much.

**Comment by tueda** [comment]
When I run FORM as a subprocess with pipes, I call something like (in the child side spawned by `fork`)
```
  system("form -pipe 3,6 init.frm");
```
(possibly with more options `-q`, `-M`, `-D...` etc.) and so the question was whether or not an auxiliary start file `init.frm` is avoidable (by use of stdin or `/dev/fd`, for example). But the discussion gave me an impression that it is actually difficult for now, and `init.frm` is a necessary evil.

**Comment by tueda** [comment]
Actually, if FORM could accept `stdin` as the input, I don't need to create pipes. I can just communicate with FORM via `stdin` and `stdout`. (Though FORM doesn't use `stderr` and errors and other logs are also put into `stdout`, which forces one to distinguish results from possible error messages.)

**Comment by tueda** [comment]
I mean `stdin` and `stdout` are not `tty`, piped to some file descriptor accessible in the parent process.

**Comment by tueda** [comment]
I'll close this, as the PR has been merged (though it introduced a bug to TFORM).
