### ISSUE TITLE
Reduction identities in the color package - trace over ten or more generators

### ISSUE THREAD

**Issue by antoncyrol** [vermaseren/form#275]
Hi,

I am having some trouble with the color package (which is hopefully not only caused by my stupidity):

Specifically, I am trying to reproduce the examples in Appendix C / Table 11 of arXiv:hep-ph/9802376  (traces of the type Tr(T_R^1 · · · T_R^n T_R^1 · · · T_R^n)). Using the color package, I can successfully reproduce the results up to n=4. However, for n>4 I get (correct) results but they still contain structure constants / f's, i.e., the reduction identities have not been applied. If I understand arXiv:hep-ph/9802376 correctly, they should be automatically applied? If so, why aren't they?

Here is my code 

```
#include- color.h

Off statistics;

*** declaring adjoint group indices ***
AutoDeclare Index ac;

*** declaring fundamental group indices ***
AutoDeclare Index fc;

.sort


*** Input ***

Local eightT=T(fc1,fc2,ac1)*T(fc3,fc4,ac1)*T(fc2,fc5,ac2)*T(fc4,fc6,ac2)*T(fc5,fc7,ac3)*T(fc6,fc8,ac3)*T(fc7,fc3,ac4)*T(fc8,fc1,ac4);
Local tenT=T(fc1,fc2,ac1)*T(fc3,fc4,ac1)*T(fc2,fc5,ac2)*T(fc4,fc6,ac2)*T(fc5,fc7,ac3)*T(fc6,fc8,ac3)*T(fc7,fc9,ac4)*T(fc8,fc10,ac4)*T(fc10,fc1,ac5)*T(fc9,fc3,ac5);

print;
.sort


*** Perform color trace ***
#call color

print;
.end
```

and the result is

```
   eightT =
      NA*I2R*cR^3 - 3*NA*I2R*cA*cR^2 + 11/4*NA*I2R*cA^2*cR - 19/24*NA*I2R*cA^3
       + cOlpR1.cOlpA1^4;

   tenT =
      NA*I2R*cR^4 - 5*NA*I2R*cA*cR^3 + 35/4*NA*I2R*cA^2*cR^2 - 155/24*NA*I2R*
      cA^3*cR + 125/72*NA*I2R*cA^4 + 5*cOlpR1.cOlpA1^4*cR - 20/3*
      cOlpR1.cOlpA1^4*cA + 2*f(cOlpR1,cOlpA1,N1_?)*f(cOlpR1,cOlpA1,N1_?)*
      cOlpR1.cOlpA1^2 + 1/12*f(cOlpA1,ac3,N1_?)*f(cOlpA1,ac3,N2_?)*f(cOlpA1,
      N1_?,N3_?)*f(cOlpA1,N2_?,N3_?)*I2R + 1/12*f(cOlpA1,ac4,N1_?)*f(cOlpA1,
      ac4,N2_?)*f(cOlpA1,N1_?,N3_?)*f(cOlpA1,N2_?,N3_?)*I2R + 1/6*f(cOlpA1,ac5
      ,N1_?)*f(cOlpA1,ac5,N2_?)*f(cOlpA1,N1_?,N3_?)*f(cOlpA1,N2_?,N3_?)*I2R;
```

Many thanks in advance,
Antonn

**Comment by vermaseren** [comment]
Hi,

You may still have to call the procedures adjoint and/or simpli
That gets it down further.

Cheers

Jos

**Comment by antoncyrol** [comment]
Hi,
very good, `#call simpli` solves it.
Thanks again,
Anton
