### ISSUE TITLE
parform build of todays git checkout

### ISSUE THREAD

**Issue by alexmyczko** [vermaseren/form#294]
parform normally says:
$ parform
ParFORM 4.2 (Sep 14 2017) 64-bits
No filename specified in call of FORM
  0.00 sec + 0.00 sec: 0.00 sec out of 0.05 sec

but taking the actual version out, I get:
$ parform
[host] *** An error occurred in MPI_Finalize
[host] *** reported by process [2037841921,0]
[host] *** on a NULL communicator
[host] *** Unknown error
[host] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
[host] ***    and potentially your MPI job)

**Comment by alexmyczko** [comment]
my build log is here, maybe i've not seen something with mpi...
http://phd-sid.ethz.ch/debian/form/

**Comment by tueda** [comment]
Well, I don't see any build log files except `config.log`, which seems rather OK (with little information).

To confirm whether it is really an environmental problem or not, you could try to build a version that you succeeded to run, with your current environment. If the old ParFORM can be built and works fine, then you could `git bisect` to identify the problematic commit.

If the old ParFORM doen't work anymore, this may mean something has happened by a system upgrade, for example upgrading MPI software version could introduce something incompatible with ParFORM...

**Comment by alexmyczko** [comment]
The build log is http://phd-sid.ethz.ch/debian/form/form_4.2.0%2Bgit20181011-1_amd64.build
Thanks for the tips, it might pretty well be related to the MPI software...

**Comment by alexmyczko** [comment]
Oh, suddenly it works again...

$ parform
ParFORM 4.2 (Oct 11 2018) 64-bits
No filename specified in call of FORM
  0.05 sec + 0.00 sec: 0.05 sec out of 0.72 sec

**Comment by tueda** [comment]
Good to hear that!

**Comment by vermaseren** [comment]
Was this on your laptop or on a machine managed by a department?
But good that it works again.

Jos
