### ISSUE TITLE
Too many gcc warnings

### ISSUE THREAD

**Issue by tueda** [vermaseren/form#298]
At some point we need to think about [warnings by gcc7/8](https://travis-ci.org/tueda/form-build-test/jobs/445141800), which claims FORM source is misleading etc. (See also [which gcc versions](https://repology.org/metapackage/gcc/versions) many people may use.)

Options:
1. keep ignoring them, though we may miss some important warning slipping in them,
2. suppress the warnings by compiler options and keep FORM source being misleading, or
3. demystify FORM source.

**Comment by vermaseren** [comment]
In principle option 3 is best, although if you talk about hundreds of messages that may be
a lot of work. I do like to keep the code ‘clean’.

**Comment by tueda** [comment]
If I search `warning:` in that page, there are 103 matches. This number is for FORM + TFORM, so about 50 warnings to be cleaned :-)

**Comment by vermaseren** [comment]
Sounds doable. Probably mostly the same construction.
How do I get the compiler that does this either on my Mac or on one of the Nikhef computers?

**Comment by tueda** [comment]
I guess you still have Homebrew on you mac, and it has now [gcc 8.2.0](https://github.com/Homebrew/homebrew-core/blob/master/Formula/gcc.rb).

**Comment by vermaseren** [comment]
OK, It did indeed install and I managed to remove those warnings. Most were of the type that it did not like
   while ( *s ) s++; s++;
but wanted the second s++; on a new line.
At the moment it translates again (on my MacBook) without warnings.

**Comment by vermaseren** [comment]
Those were all the warnings my system gave.
Maybe there are some extra compiler settings that give those extra warnings.
Once I can reproduce them here, I can attack them.

**Comment by tueda** [comment]
Maybe you don't use the `-Wextra` option, which enables some extra warning options. With that option, you will see many warnings, though we can argue if it is more harm than good and not needed.

**Comment by tueda** [comment]
> Why do they issue warnings about it?

Because people consider it as a design defect in C and implicit use of it is most likely a bug by the programmer. See [this page](https://developers.redhat.com/blog/2017/03/10/wimplicit-fallthrough-in-gcc-7/) for why and how to fix it. C++17 has the standard way to declare an fall-through is intended. Probably C2x will also do so.

But maybe we can switch off "implicit-fallthrough" warnings for now.

By the way, if you put the `-pedantic` option you will get more warnings because FORM is not standard compliant.

**Comment by vermaseren** [comment]
I will commit/push the -Wextra problems. But the -Wpedantic will have to wait.
I did have a look at it and it concentrates purely around pointers to functions
not being allowed to be cast to ther pointers. A nice fraction can be intercepted
I believe by changing a few declarations in the structs, but I better think this 
over first.

**Comment by vermaseren** [comment]
One problem.
I checked, before committing my changes, that it still works with the old compiler.
I added everywhere   
__attribute__ ((fallthrough));
and now the old compiler complains that the declaration does not declare anything.
[-Wmissing-declarations].
Hence: that is not a good fix of those guys.
Suggestions?

**Comment by tueda** [comment]
Maybe just writing [`/* fall through */`](https://github.com/torvalds/linux/search?q=fall+through&unscoped_q=fall+through&type=Code) or [`/* FALLTHROUGH */`](https://github.com/torvalds/linux/search?q=FALLTHROUGH&unscoped_q=FALLTHROUGH&type=Code) would be enough? If it turns out to be not so good, later we can replace such phrases with an attribute or something.

**Comment by vermaseren** [comment]
Yes, I just found that one with google.
I have already tried it in one file and it seems to work. It turns out that the new compiler
does try to see whether the fall through was intended by looking for commentary.
I consider this a bit dirty I must say.
I’ll fix it up and commit once I am happy with it. The pedantic is not for now.

**Comment by tueda** [comment]
I guess most of the warnings are removed (except `-Wmaybe-uninitialized` of gcc7). So I close this issue.
