### ISSUE TITLE
Test fails on SLC5 due to old Ruby

### ISSUE THREAD

**Issue by tueda** [vermaseren/form#299]
The [test suite fails](https://travis-ci.org/tueda/form-build-test/jobs/447059977) on Scientific Linux CERN 5, because `Dir::mktmpdir` is unavailable before 1.8.7 but the configure script doesn't check it.

Perhaps an alternative is needed or we can just make the configure script reject Ruby < 1.8.7; it's too old.

**Comment by vermaseren** [comment]
I guess your perhaps sounds best.
We cannot keep up with new compiler requirements (see all the new warnings we had
to take care of) and at the same time be infinitely backwards compatible.

**Comment by tueda** [comment]
Now we require Ruby >= 1.9 (https://github.com/vermaseren/form/commit/f23dc06468f3802014df386d2ae9a7c326de2e6e). The problem of `Dir::mktmpdir` should not occur.
