### ISSUE TITLE
Does FORM compile on Windows 10?

### ISSUE THREAD

**Issue by vsht** [vermaseren/form#342]
Some time ago I was helping a person to overcome the limitations of Mathematica and provided a solution that uses FORM. However, it turned out that the person uses Windows 10 and so it was not possible to use FORM straight away since there are no precompiled binaries available.

A few days later I also tried to compile FORM via cygwin 64-bit  on Windows 10 (the full developer collection was installed) and failed as well (the compilation started but broke down at a rather early stage). I don't use Windows on a regular basis, but I remember that on Windows 7 the compilation was straight forward.

So my question is whether Windows 10 is officially supported and whether someone from the dev
team is willing to look into the issue. If that is so, I could provide more details (full logs) and play a guinea pig to help get things working.

**Comment by tueda** [comment]
I'm a Windows user but have switched from Cygwin to Ubuntu with WSL for daily work.

So, I've just tried to compile the latest FORM source with Cygwin 64-bit on Windows 10. There is no problem, except the fact that some tests fail: `Test_ExtComm_1` times out (expected be rather slow) and `Fun_distrib_1` due to `No memory while allocating` with TFORM (expected to be a memory hog).

What was the error you encounted?

**Comment by vsht** [comment]
Thanks a lot for your reply. I tried again after my old W10 installation died and this time it seems to work. I think the problem was that I was trying to use `minigw` instead of `gcc` or a 32-bit version of `gcc`. My bad. 

So to add some useful information to this issue, let me provide a short tutorial for the benefit of other users and as a memo for myself.

1. Download the 64-bit version of cygwin: https://cygwin.com/setup-x86_64.exe
2. When installing the packages, add the following items in addition to the already selected packages:
`automake`, `autoconf`, `git`, `libtool`, `gcc-g++`, `make`
3. Open Cygwin64 terminal and issue the following sequence of commands
```
git clone https://github.com/vermaseren/form.git
autoreconf -i
./configure --disable-dependency-tracking
make
```
4. If the compilation is successful, you should be able to evaluate
```
cd sources
./form.exe
``` 
5. Now you can pick up `form.exe` and `tform.exe` from `C:\cygwin64\home\userName\form\sources`
and use the binaries in the usual way.

Tested on Windows 10 Professional 1909.

Sorry for the noise.
