### ISSUE TITLE
A way to clear extrasymbol definitions?

### ISSUE THREAD

**Issue by jodavies** [vermaseren/form#347]
As far as I know, there is no way to clear definitions of extrasymbols. I regularly use a construction like
```
Bracket x;
.sort
Collect coll;
ArgToExtraSymbol coll;

* many modules involving x

Identify coll(x?) = x;
FromPolynomial;
```

If the expression is large enough for disk-based sorting and there are many modules to work through, this can provide a large performance improvement, trading some memory usage (for the extrasymbol definitions) for much faster sorts.

The problem is now that if I want to do this many times with a loop or procedure calls etc, the extrasymbol definitions use too much memory and lead to crashes.

It would be useful if there were a way to do something like `#clearextrasymbols` which one can use when they know they have no further use for the current extrasymbol definitions, and the next `ArgToExtraSymbol` will start again with `Z1_`.

Thanks,
Josh.

**Comment by benruijl** [comment]
This feature is probably not that hard to add since there is an instruction
to clear the extra symbols of the code optimization already.

**Comment by tueda** [comment]
`Delete extrasymbols;`?

**Comment by jodavies** [comment]
Oh, great! I didn't know about that...
