### ISSUE TITLE
Puzzling behavior of factarg (freezes etc.)

### ISSUE THREAD

**Issue by vsht** [vermaseren/form#353]
Perhaps it is my lack of understanding of `factarg`, but I'm wondering
why the following simple code

```
CF f;
S p1,p2;

L exp = f(-p1-p2);

factarg,(0),f;
print;
.end
```
makes FORM freeze? Modifying the argument slightly 
```
CF f;
S p1,p2;

L exp = f(p1+p2);

factarg,(0),f;

print;

.end
```
outputs 

```
   exp =
      162000*f*pi_*p1;
```
which is even more weird. An if p1 and p2 are promoted to vectors, then with 
```
CF f;
V p1,p2;

L exp = f(p1+2*p2);

factarg,(0),f;

print;

.end
```
I get
```
!!!This $ variation has not been implemented yet!!!
Called from execarg
Program terminating at /home/vs/Downloads/FORM-test-script.frm 
Line 8 --> 
```

All these examples work properly if I employ `normalize,(0),f;` instead of `factarg,(0),f;` which is also sufficient
for what I'm interested in. Still, since the documentation (p.86) says
```
`(0) Eliminates the coefficient of the term in the argument. Similar to Normalize,(0),....
```
I though that both statements should produce similar results.

Cheers
Vladyslav

**Comment by jodavies** [comment]
For me your example simply hangs, with nothing useful from valgrind.

**Comment by tueda** [comment]
Your second example (weird `pi_`) sounds like #140.

**Comment by tueda** [comment]
Actually, [form 4.0.0](https://github.com/tueda/homebrew-form/blob/master/form%404.0.0.rb) (FORM 4.0 (Mar 29 2012)) gives the same results for your 3 examples (freeze, `162000*f*pi_*p1` and `!!!This $ variation has not been implemented yet!!!`).

**Comment by vermaseren** [comment]
It seems that the(0) option had never been tested on the case that no factor needed to be divided out. The latest commit should take care of it.

**Comment by vsht** [comment]
Great, many thanks!

**Comment by tueda** [comment]
I'm confused; to me, none of the above examples still doesn't work and behaves erroneously, though something seemed to be done in 9b0b89b8d856cd563d72543b04ed5da2c05c60f7... For example:
```
$ ./vorm test.frm
FORM 4.2.1 (Jul 15 2020, v4.2.1-9-g9b0b89b) 64-bits  Run: Fri Jul 17 18:20:17 2020
    CF f;
    S p1,p2;

    L exp = f(p1+p2);

    factarg,(0),f;

    print;

    .end

Time =       0.00 sec    Generated terms =          1
             exp         Terms in output =          1
                         Bytes used      =         56

   exp =
      162000*f*pi_*p1;

  0.00 sec out of 0.00 sec
```

**Comment by vsht** [comment]
Sorry, I didn't have time to check it yesterday and I assumed that if this specific issue
was mentioned then the examples will for sure work.

I agree with Takahiro, it seems that all of the original code samples still do not work
as they should.

**Comment by tueda** [comment]
Now it seems to work.
