### ISSUE TITLE
Cannot create more than 509 table files

### ISSUE THREAD

**Issue by zhaoli-IHEP** [vermaseren/form#357]
Here is the test script
```form
#-
symbol j;
CFunction ff;
Table,sparse,[test_table](1);

Local expression = sum_(j,1,100,ff(j));
.sort

#do idx = 1,1000

bracket ff;
.sort
fillexpression [test_table] = expression(ff);
.sort
TableBase "test`idx'_table.tbl" create;
TableBase "test`idx'_table.tbl" addto [test_table];
.sort

#enddo

.end
```
Then it stoped with the error "Could not create new file test510_table.tbl"

**Comment by vermaseren** [comment]
This seems to be a restriction of the operating system.
Form does a call to the C function fopen and gets back the message that the file could not be opened.
If Form would like to avoid this, it would mean opening and closing files each time an operation to
a tablebase is done. That is very wasteful.
Try to deal with the tablebases in such a way that you can finish with a number of them and close
those before working with the other ones.
Alternatively you could try to figure out how to raise this limit of open files in your operating system.

Sorry I cannot help you more.

Jos

**Comment by zhaoli-IHEP** [comment]
> This seems to be a restriction of the operating system. Form does a call to the C function fopen and gets back the message that the file could not be opened. If Form would like to avoid this, it would mean opening and closing files each time an operation to a tablebase is done. That is very wasteful. Try to deal with the tablebases in such a way that you can finish with a number of them and close those before working with the other ones. Alternatively you could try to figure out how to raise this limit of open files in your operating system. Sorry I cannot help you more. Jos
> […](#)

Thank you for the explanation. But how to close the file. I tried the #close, but it does not work.

**Comment by vermaseren** [comment]
Now you mention it, there is indeed no command for that, because then you could not use
its elements anymore. It would have to involve clearing out the complete table from the memory.
There is somewhere in the operating system a parameter for the number of open files that a
process can have. But it will probably need superuser status to change it and it may need
rebooting. I remember from the past that it used to be much smaller.

Jos

**Comment by jodavies** [comment]
Indeed, my distribution has a default max open file limit of 1024 (`unlimit -a` to check). If I double it to 2048, I can run your example with no errors.
