### ISSUE TITLE
Replacing power sign using dictionaries

### ISSUE THREAD

**Issue by spj101** [vermaseren/form#358]
The [FORM manual](https://www.nikhef.nl/~form/maindir/documentation/reference/online/online.html#SECTION001400000000000000000) states that dictionaries can be used to replace the power sign in an expression. However, I can't seem to get this to work correctly.

The following program:
```
Symbols x;
#OpenDictionary test
  #add ^:"**"
#CloseDictionary
Local F = x^2;
#UseDictionary test
Print;
.end
```

Outputs:
```
F = x^2;
```

Rather than the expected:
```
F = x**2;
```

Is this a bug or am I misunderstanding how to use dictionaries?

**Comment by vermaseren** [comment]
See answer to #358

Jos

**Comment by spj101** [comment]
Thankyou @vermaseren for fixing this so quickly! It seems to be working correctly for me.
