### ISSUE TITLE
Form not installed in macOS Catalina 

### ISSUE THREAD

**Issue by arindamdasphysics** [vermaseren/form#381]
Dear Form Team, 

I was trying to install Form in MacOS Catalina and MacPorts. After performing 

autoreconf -i
./configure
make

without any issue, I was trying to perform 'make install' which stopped with the following error message : 

Making install in doxygen
make[3]: Nothing to be done for `install-exec-am'.
make[3]: Nothing to be done for `install-data-am'.
Making install in manual
make[3]: Nothing to be done for `install-exec-am'.
make[3]: Nothing to be done for `install-data-am'.
Making install in devref
make[3]: Nothing to be done for `install-exec-am'.
make[3]: Nothing to be done for `install-data-am'.
make[3]: Nothing to be done for `install-exec-am'.
 .././build-aux/install-sh -c -d '/usr/local/share/man/man1'
 /usr/bin/install -c -m 644 form.1 '/usr/local/share/man/man1'
Making install in sources
[ -f version.h ] || ln -s "./version.h.in" version.h
[ -f version.h ] || ln -s "./version.h.in" version.h
 .././build-aux/install-sh -c -d '/usr/local/bin'
  /usr/bin/install -c form tform '/usr/local/bin'
install: /usr/local/bin/form: Permission denied
make[2]: *** [install-binPROGRAMS] Error 71
make[1]: *** [install-am] Error 2
make: *** [install-recursive] Error 1

Could you please help to solve this issue. 
Many thanks for your time and consideration.

Regards, 
Arindam

**Comment by tueda** [comment]
I'm not so sure about MacOS Catalina and MacPorts, but do you have the root privilege to install FORM to `/usr/local/` (if you really want to do this)? On Linux, it may be done by `sudo make install`, though the FORM binary is a single file, and so you can just run it.

**Comment by arindamdasphysics** [comment]
Dear Takahiro, 

Many thanks for the kind and quick reply. I am sorry for the late response. 
I was testing different ways. Now I have installed Form locally 

autoreconf -I
./configure --prefix=/Users/home1/Form/form1
make
make install

and attached the path in ~/.zshrc of the Catalina:

export PATH=/Users/home1/Form/form1/bin:$PATH

It passed make check. 

I have tested form for a 2 -> 2 process and it is working fine. 

Regards,
Arindam

**Comment by tueda** [comment]
Glad to hear that it works and now you can use FORM!

FYI: Probably the MAN file has been installed in `/Users/home1/Form/form1/share/man`. If you add this path to `$MANPATH` then `man form` will show the command-line options, though this is not necessary and these options can be easily found in the reference manual on the web site.
