### ISSUE TITLE
Expressions simplification

### ISSUE THREAD

**Issue by kikke88** [vermaseren/form#398]
Dear FORM community,

I am trying to use FORM for coefficient simplification. The general case of the coefficient is shown below.
<img src="https://latex.codecogs.com/png.latex?%5Cfn_cm%20%5Clarge%20%5Cfrac%7B%5Cfrac%7BPoly_1%7D%7BPoly_2%7D%20%5Ccdot%20%5Cfrac%7BPoly_3%7D%7BPoly_4%7D%7D%7B%5Cfrac%7BPoly_5%7D%7BPoly_6%7D%7D">
Where Poly_i are polynomials from a known set of symbols. After all simplifications, the result has the form of a fraction of the polynomials.

For example,
<img src="https://latex.codecogs.com/png.latex?%5Cfn_cm%20%5Clarge%20%5Cfrac%7B%286%20%5Ccdot%20x%20&plus;%203%29%7D%7B2%20%5Ccdot%20y%7D%20%5Ccdot%20%5Cfrac%7B11%7D%7B3%5Ccdot%20z%20&plus;%209%7D%20%3D%20%5Cfrac%7B11%20%5Ccdot%20%282%20%5Ccdot%20x%20&plus;%201%29%7D%7B2%20%5Ccdot%20y%20%5Ccdot%20%28z%20&plus;%203%29%7D">
<img src="https://latex.codecogs.com/png.latex?%5Cfn_cm%20%5Clarge%20%5Cfrac%7B3%7D%7B2%7D%20%5Ccdot%20d%20-%20%5Cfrac%7B%5Cfrac%7B3%7D%7B2%7D%20%5Ccdot%20d%5E2%7D%7Bd-2%7D%20&plus;%20%5Cfrac%7B6%20%5Ccdot%20d%7D%7Bd-2%7D%20-%20%5Cfrac%7B6%7D%7Bd-2%7D%20-%203%20%3D%200">

Is there a way to make such simplifications in FORM?
I have not been able to achieve the desired result (maybe I misused PolyRatFun and #Optimize)

Thanks in advance.

**Comment by tueda** [comment]
The following program does more or less what you want, I think:
```form
CF num,den,rat;
S x,y;

#procedure PolySimplify()
  .sort:PolySimplify-1;
* Enable PolyRatFun. Convert num and den into rat.
  PolyRatFun rat;
  id num(x?) = rat(x,1);
  id den(x?) = rat(1,x);
  .sort:PolySimplify-2;
* Disable PolyRatFun. Convert rat back to num and den and then factorise num and den.
  PolyRatFun;
  id rat(x?,y?) = num(x) * den(y);
  factarg num;
  factarg den;
  chainout num;
  chainout den;
#endprocedure

S x,y,z,d;

L F1 =
  + num(6 * x + 3) * den(2 * y) * num(11) * den(3 * z + 9)
;

L F2 =
  + num(3 / 2 * d)
  - num(3 / 2 * d^ 2) * den(d - 2)
  + num(6 * d) * den(d - 2)
  - num(6) * den(d - 2)
  - num(3)
;

#call PolySimplify()

P +s;
.end
```
```
   F1 =
       + num(11)*num(1 + 2*x)*den(2)*den(y)*den(3 + z)
      ;

   F2 = 0;
```
Here, the `num` and `den` functions are used for representing factors in the numerator and those in the denominator.

Note that if you simply give rational polynomials as, for example, `1 / (1 + x)`, then it is internally expressed with some functions but printed just as `1 / (1 + x)`, which may cause some confusion (and actually relatively buggy).

**Comment by kikke88** [comment]
Thank you very much for your help.
All that remains is to come up with a regex pattern to replace the original expression with an expression with num(...) and den(...) :)

**Comment by jodavies** [comment]
You can use `Denominators` to convert the `/()` notation into, say, `den()` and then go from there. You can move the symbols into the `PolyRatFun` with `Identify` statements, so you don't need to prepare the input with `num` and `den` functions already.

You can modify tueda's procedure to something like
```
#procedure PolySimplify()
  .sort:PolySimplify-1;
* Enable PolyRatFun. Convert num and den into rat.
  PolyRatFun rat;
  denominators den;
  id num(x?) = rat(x,1);
  id den(x?) = rat(1,x);
  id x? = rat(x,1);
  .sort:PolySimplify-2;
* Disable PolyRatFun. Convert rat back to num and den and then factorise them.
  PolyRatFun;
  id rat(x?,y?) = num(x) * den(y);
  factarg num;
  factarg den;
  chainout num;
  chainout den;
#endprocedure
```

**Comment by tueda** [comment]
@jodavies good catch! I think in general `id many, x?^y? = rat(x^y,1);` is needed to handle `x * y` and `1 / x`.

So, here is a revised complete example:
```form
CF num,den,rat;
S x,y;

#procedure PolySimplify()
  .sort:PolySimplify-1;
* Enable PolyRatFun. Convert num and den into rat.
  PolyRatFun rat;
  denominators den;
  id num(x?) = rat(x,1);
  id den(x?) = rat(1,x);
  id many,x?^y? = rat(x^y,1);
  .sort:PolySimplify-2;
* Disable PolyRatFun. Convert rat back to num and den and then factorise them.
  PolyRatFun;
  id rat(x?,y?) = num(x) * den(y);
  factarg num;
  factarg den;
  chainout num;
  chainout den;
#endprocedure

* Examples

S x,y,z,d;

L F1 =
  + (6 * x + 3) / (2 * y) * 11 / (3 * z + 9)
;

L F2 =
  + 3 / 2 * d
  - 3 / 2 * d^2 / (d - 2)
  + 6 * d / (d - 2)
  - 6 / (d - 2)
  - 3
;

L F3 =
  + (1 + x * y^3) / (z + x * y^3 * z)
  - 1 / z
;

#call PolySimplify()

P +s;
.end
```
```
   F1 =
       + num(11)*num(1 + 2*x)*den(2)*den(y)*den(3 + z)
      ;

   F2 = 0;

   F3 = 0;
```

**Comment by kikke88** [comment]
The program you suggested does its job perfectly for the case of a simple fraction, but in the case of a complex fraction (see example), after replacing den with rat, an error occurs: "...polyratfuns must contain symbols only"
<img src='https://latex.codecogs.com/svg.image?%5Cfrac%7BPoly_1%7D%7B%5Cfrac%7BPoly_2%7D%7BPoly_3%7D%7D%20%5Cto%20%5Cfrac%7BPoly_1%7D%7Bden(%5Cfrac%7BPoly_2%7D%7Bden(Poly_3)%7D)%7D'>
Сoefficient examples:
`-(-d*s+3*s)/(-1/(d-4)*d^2*s+6/(d-4)*d*s-9/(d-4)*s)`
`((3 * x + 2) / (4 * y)) / (21 / (2 * x + 8) + z / (2 * x + 8) + z^3)`

**Comment by vermaseren** [comment]
Your problem is that you have denominators inside denominators.
Because such denominators are functions you get that message.
If d-4 is a symbol you should have no problem.

**Comment by jodavies** [comment]
You can use "ExtraSymbols" to represent the denominators inside the polyratfun. Once things have been simplified, you can insert their definitions:
```
PolyRatFun prf;                  
Denominators den;                
                                 
Argument den;                    
   ArgToExtraSymbol den;         
   Identify den(x?) = 1/x;       
EndArgument;                     
                                 
Identify den(x?) = prf(1,x);     
Identify,many x?^y? = prf(x^y,1);
.sort                            
                                 
Argument prf;                    
   FromPolynomial;               
EndArgument;                     
```

Probably this code doesn't do what you want if there are doubly-nested denominators...
