### ISSUE TITLE
Finding right setup parameters

### ISSUE THREAD

**Issue by kikke88** [vermaseren/form#406]
Dear FORM community,

I have a C++ program that sometimes has coefficients (fractions with polynomials), which need to be simplified. It uses fork and execl to start `form` and communicates with `form` through the pipes. The program sends the coefficient to `form`, waits for its simplification with https://github.com/vermaseren/form/issues/398#issuecomment-971587108 and reads the result. Then the program sends the next coefficient and everything repeats
The working time of the main program can be calculated in weeks, which means that a very large number of coefficients is simplified, and the size of the coefficients can exceed 100'000 characters. 

When simplifying large coefficients, I have seen such errors:
1)
```
ERROR: PolyRatFun doesn't fit in a term
(1) num size = 45232, den size = 9292,  MaxTer = 160000
```
I have increased MaxTermSize to 10MB.

2)
```
=== Workspace overflow. 40000000 bytes is not enough.
=== Change parameter WorkSpace in form.set
```
I have increased WorkSpace to 1GB.

3)
```
(1)Output should fit inside a single term. Increase MaxTermSize?
Called from EndSort
```
I could not find the MaxTermSize and WorkSpace values at which the program would work. I read the entire 17th chapter of the documentation, but I couldn't figure out what another settings could help me with this error.

- Please tell me which setup parameters I need to change and to what values so that in the described situation `form` works without errors?
- Why .str files are always empty, can using them help?

(In the attached archive .frm and .set files on which I get the error)
Thanks in advance.

[example.zip](https://github.com/vermaseren/form/files/8379053/example.zip)

**Comment by jodavies** [comment]
The problem is that the intermediate "incomplete simplification" caused by the `.sort` on your line 28 is really enormous.

This `.sort` isn't actually necessary, I think, and if you remove it your test file runs with the default memory parameters.

**Comment by tueda** [comment]
> This `.sort` isn't actually necessary, I think, and if you remove it your test file runs with the default memory parameters.

Good point! I was trying to increase the buffer sizes: with that `.sort`, at least `MaxTermSize=200M` and `WorkSpace=50G` (1TB memory allocated) was not sufficient...

**Comment by jodavies** [comment]
Removing that sort is not a guaranteed fix, I suppose, since one can surely construct nested input which will cause the same problem in the first iteration through the `FromPolynomial` loop which follows. That one is necessary, however...

**Comment by kikke88** [comment]
Thanks a lot for the advice, deleting `.sort` really helped. But the program began to fall on very simple coefficients `2/((8*d*s^3+16*d*s^2-40*s^3-80*s^2)/(d-4))`.  "ERROR: polynomials and polyratfuns must contain symbols only". As I understand it, this is because of the characters generated by `ArgToExtraSymbol`

**Comment by jodavies** [comment]
OK, then this sort is necessary for sufficiently nested input. One solution is to help reduce the number of extrasymbols produced by bringing things to a more minimal form first. Adding after `Denominators den;`:
```
FactArg den;
ChainOut den;
Normalize,^-1 den;
Repeat Identify den(den(x?)) = x;
.sort
```
seems to work for all of your test cases, for me.
