### ISSUE TITLE
Unresolved setelement during substitution

### ISSUE THREAD

**Issue by TomSteu** [vermaseren/form#407]
Dear FORM team,

I've encountered a curious issue today, I wrote some code that terminated a long computation with
 `Unresolved setelement during substitution`. I think this is happening on calling `.sort` or `.end`.

Unfortunately, I am quite puzzled by this -- I can get collect a very long list of terms with `print "%t";` (`print;`alone  does not work, the error occurs before the output) but I am not sure what to look for in there.

Could you guys give me a hint what this error means, then I can construct some minimal case where things go wrong. Sorry for not providing a sample of code.

cheers,
Tom

**Comment by tueda** [comment]
Well, what I can say for now is maybe: do you use any wildcard substitutions with sets? The error message looks related to something wrong that happened during them.

For your information: the error message is in `ResolveSet` (`wildcard.c`)

https://github.com/vermaseren/form/blob/2a37fd21dd22e7f1a90c4956c4adf50555f7bd07/sources/wildcard.c#L1363

which is only called in `WildFill`:

https://github.com/vermaseren/form/blob/2a37fd21dd22e7f1a90c4956c4adf50555f7bd07/sources/wildcard.c#L611

**Comment by vermaseren** [comment]
This error occurs typically when you have wildcarding involving set elements as in:
Symbols a1,…,a9,x,n;
Set aa:a1,…,a9;

id x^n? = aa[n];

If the wildcard n gets a value outside the range 1 to 9 you will get this error message.
The safe code would be
if ( ( count(x,1) > 0 ) && ( count(x,1) <= 9 ) );
    id x^n? = aa[n];
else;
*  either print here a message that tells that something unexpected happened
*  or continue without the substitution.
endif;

I hope this helps.

**Comment by tueda** [comment]
> This error occurs typically when you have wildcarding involving set elements as in: Symbols a1,…,a9,x,n; Set aa:a1,…,a9; id x^n? = aa[n];

I guess this is a bit different problem: running
```form
Symbols a1,...,a9,x,n;
Set aa:a1,...,a9;
Local F = x^10;
id x^n? = aa[n];
.end
```
gives a different error:
```
Array bound check during set substitution
    value is 10
Program terminating at test.frm Line 4 -->
```

which is in

https://github.com/vermaseren/form/blob/2a37fd21dd22e7f1a90c4956c4adf50555f7bd07/sources/wildcard.c#L1434-L1435

The problem with `Unresolved setelement ...` occurs before coming the label `GotOne`. (I have no experience with this error message and have no ideas what the code is doing...)

**Comment by TomSteu** [comment]
Thank you for the hints, I found my mistake. It was indeed some nonsense with a half-integer set position like this:
```

Symbols a1,...,a9,n;
CFunction cfun;
Set aa:a1,...,a9;

Local F = cfun(1/2);

id cfun(n?) = aa[n];
.end
```
