### ISSUE TITLE
How to access the Multiple Zeta Value Data Mine?

### ISSUE THREAD

**Issue by althit2022** [vermaseren/form#411]
Can't access the MZV Data Mine at https://www.nikhef.nl/~form/maindir/maindir.html.
Says access is forbidden.
"You don't have permission to access /~form/datamine/datamine.html on this server."
Website says to use the github issue tracker to report any problems.

Thx for any help.

**Comment by vermaseren** [comment]
I cannot get in that way either.
I passed the problem to the Nikhef helpdesk. Let us see what they say, because
via the form account I can get into those pages.

Jos

**Comment by althit2022** [comment]
Jos,
Thanks for following up.Much appreciated.Looking forward to delving into the MZV Data Mine sometime!
Cheers,Greg.

    On Saturday, August 20, 2022 at 03:09:13 PM PDT, Jos Vermaseren ***@***.***> wrote:  
 
 

I cannot get in that way either.
I passed the problem to the Nikhef helpdesk. Let us see what they say, because
via the form account I can get into those pages.

Jos

**Comment by tueda** [comment]
I close this issue because this seems to work now: https://www.nikhef.nl/~form/datamine/datamine.html.
