### ISSUE TITLE
FORM compatibility

### ISSUE THREAD

**Issue by deepnee** [vermaseren/form#450]
Is FORM compatible with windows 8? I am unable to install it on windows 8.

**Comment by tueda** [comment]
Windows is not officially supported. But it may work if you have a Unix-like environment (e.g., [Cygwin](https://www.cygwin.com/)) and if you build it from the source.

If you really need a native Windows executable (without POSIX), then the `--with-api=windows` option should be passed to `configure`.

**Comment by jodavies** [comment]
Windows Subsystem for Linux is also a good option here.

**Comment by benruijl** [comment]
Can you provide us with the error? What have you tried?

**Comment by deepnee** [comment]
Please let me know is a laptop with 4 GB RAM enough to install FORM or not. What should be the minimum memory size of the RAM?

**Comment by benruijl** [comment]
4GB should be enough. Probably < 1 GB would be enough too.
