### ISSUE TITLE
Please tell me whether my hp laptop with the following hardware system specifications is compatible with FORM or not

### ISSUE THREAD

**Issue by deepnee** [vermaseren/form#452]
Processor: Intel(R) Core(TM) i3-3110M CPU @ 2.40GHz 2.40GHz
RAM: 4.00GB(3.89GB usable)
System type: 64-bit Operating System, x64-based processor
Pen and touch: no pen and touch input is available for this display
Windows 8.1 single language

**Comment by benruijl** [comment]
Duplicate
