### ISSUE TITLE
Improving format mathematica?

### ISSUE THREAD

**Issue by vsht** [vermaseren/form#460]
Dear FORM developers,

I guess that all FORM users exporting their results to Mathematica are aware of the issue that happens when
naively trying to save expression with scalar products, e.g.

```
Auto V p;
Auto S s;

L exp = s1*p1.p2 + s2*p3.p4^2 + s3*p3.p4^3;

.sort 
Format Mathematica;
print;
.end
```
This yields
```
 p1 . p2*s1 + p3 . p4^2*s2 + p3 . p4^3*s3
```
which Mathematica happens to interpret as 
```
Plus[Times[s1,Dot[p1,p2]],Times[s2,Dot[p3,Power[p4,2]]],Times[s3,Dot[p3,Power[p4,3]]]]
```
as compared to the correct version
```
      p1 . p2*s1 + ( p3 . p4)^2*s2 + (p3 . p4)^3*s3
```
yielding
```
Plus[Times[s1,Dot[p1,p2]],Times[s2,Power[Dot[p3,p4],2]],Times[s3,Power[Dot[p3,p4],3]]]
```
I know that one could do something like
```
repeat;
id v1?.v2? = sp(v1,v2);
id (v1?.v2?)^(-1) = pow(sp(v1,v2),-1);
endrepeat;
```
to circumvent the issue, but perhaps it could be nice if FORM could produce the right expressions right away?

Cheers,
Vlad

**Comment by tueda** [comment]
Maybe, we could always enclose dot products in parentheses, even when not needed. This may be easier to implement than enclosing or not enclosing dot products in parentheses depending on context.

For reference, operator precedence in Mathematica:

https://reference.wolfram.com/language/tutorial/OperatorInputForms.html

The binary operator `.` (`Dot`) has a lower precedence than the binary operator `^` (`Power`).

**Comment by vermaseren** [comment]
A bit confusing.
What does it do with 3.2^4 ? (floating point 3.2)
Or do you have to write that also as (3.2)^4 ?

**Comment by tueda** [comment]
I guess Mathematica treats `3.2` as an "atom". So, `3.2^4` is fine.

Indeed,
```mma
3.2^a
```
gives
```
Power[3.2`, a]
```
and
```mma
p.q^a
```
gives
```
Dot[p, Power[q, a]]
```

**Comment by vermaseren** [comment]
I do not understand why they do it this way.
What else can the . operator do?
Maybe it was planned to use it for data structs, but then it should also bind tighter.

**Comment by tueda** [comment]
The dot operator perfectly works with vectors/tensors in a reasonable way.

For example, the Mathematica code
```mma
{1, 2}.{3, 4}^2
```
gives
```
41
```

This is the same as other languages, like Python:

```python
import numpy as np

a = np.array([1, 2])
b = np.array([3, 4])

a@b**2
```
which also gives `41`, not `121`.

I think an expression $p \cdot q^2$ in math or physics papers would be understood as $p \cdot (q^2)$.
