### ISSUE TITLE
Compilation of documentation fails in case of compilation from tarball.

### ISSUE THREAD

**Issue by andriish** [vermaseren/form#462]
Compilation of documentation fails in case of compilation from tarball.

```
make: Entering directory 'T/form-4.3.1/doc'
Making pdf in doxygen
make[1]: Entering directory 'T/form-4.3.1/doc/doxygen'
[ -f version.sh ] || ln -s "./version.sh.in" version.sh
Running /usr/bin/doxygen DoxyfilePDFLATEX ...
/bin/sh: line 2: ./version.sh: No such file or directory
make[1]: *** [Makefile:555: pdflatex/doxygen.tex] Error 1
make[1]: Leaving directory 'T/form-4.3.1/doc/doxygen'
make: *** [Makefile:423: pdf-recursive] Error 1
make: Leaving directory 'T/form-4.3.1/doc'
```

Expected result: compilation of docs from the tarball suceeds.

The way to reproduce:

```
mkdir T
cd T
wget https://github.com/vermaseren/form/releases/download/v4.3.1/form-4.3.1.tar.gz
tar zxfv form-4.3.1.tar.gz 
cd form-4.3.1/
autoreconf -fi
 ./configure
make -j 10 
make -C doc pdf
```

**Comment by tueda** [comment]
Thank you for your report. I think I know what is happening with the tarball. 

In [`Makefile.am` for Doxygen](https://github.com/vermaseren/form/blob/d4a1a2962120ce9f0981123011e90ca3acc8edb0/doc/doxygen/Makefile.am), almost everything is included in an `if CONFIG_DOXYGEN` clause. This means that the version information file for Doxygen is included to a tarball only when Doxygen is available/enabled. And, the tarball was generated with Github Actions, without Doxygen.

I also found that [the fallback in `configure.ac`](https://github.com/vermaseren/form/blob/d4a1a2962120ce9f0981123011e90ca3acc8edb0/configure.ac#L17-L28) does not consider Doxygen.

I will fix these issues. For now, a workaround would be:
```bash
touch doc/doxygen/version.sh.in
```
