### ISSUE TITLE
moebius_3 test case

### ISSUE THREAD

**Issue by jodavies** [vermaseren/form#471]
I often have fails on this test with tform due to its memory consumption with tform -w8, which is 18GB or so. I see it is already disabled on github due to fails, presumably for the same reason. Maybe this one is more reliable if it only runs in serial tests?

Thanks,
Josh.

**Comment by jodavies** [comment]
In addition, currently when I run `make check` after control returns to my shell, there are some leftover processes which are stuck until I kill them. Maybe this is messing up the CI also.

**Comment by tueda** [comment]
I think you have a test case that gives `TIMEOUT` (`Issue7_3`). It seems that `check.rb` fails to kill timed-out processes. I was aware of it with WSL2 but thought it might be a WSL-specific problem.

Probably, you are working on a real Linux and hit the same problem. So, I have created an issue for it: #476
