### ISSUE TITLE
Freeze in parsing complex conjugate

### ISSUE THREAD

**Issue by tueda** [vermaseren/form#499]
FORM freezes when running the following program:
```form
S x#c;
L F = x#;
.end
```

**Comment by jodavies** [comment]
So `CodeGenerator` does not have a case for `TCONJUGATE`, which only appears twice in the whole codebase (in `token.c` and its definition in `ftypes.h`). It seems, that no one has ever used this feature?

**Comment by vermaseren** [comment]
As far as I know, nobody had been really using it.
It was created in version 1 in anticipation of a conjugation operation, but that never
materialised. Hence I must have forgotten about it when making the parser for version3
and later. For backward compatibility I never took out the conjugation #.
One can do either of two things:
1: take out this conjugation thing and see whether people complain.
2: fix up the parser.
Probably 2 is not too much work, although I have no idea whether there are still some
surprises.

**Comment by tueda** [comment]
The manual also says

> This property is only relevant, when the complex conjugation operator is used. This operator has not been implemented and currently there are no plans to do so.

I think we can just display a "not implemented" error (and that is much better than the crash/freeze).

**Comment by jodavies** [comment]
That seems reasonable, just print the error and terminate. Do you want to make the PR @tueda ?

**Comment by tueda** [comment]
@jodavies OK, I will create a PR for that.
