### ISSUE TITLE
Tensors don't accept argument field wildcards anymore

### ISSUE THREAD

**Issue by a-maier** [vermaseren/form#523]
The following code crashes with `Illegal substitution of argument field in tensor`:
```form
t t;

l foo = t;

id t(?a) = t(?a);
.end
```
Adding actual index arguments to `t` does not seem to change anything.

`git bisect` tells me that the new behaviour was introduced in 029a64708c9. Since this change is not mentioned in the commit message I assume it was not intentional?

**Comment by jodavies** [comment]
Hi Andreas,

The fix for that is coming in #519 . I think @tueda is just testing carefully.

**Comment by tueda** [comment]
OK, I'm still unsure how [a certain code path](https://coveralls.io/builds/67610421/source?filename=sources%2Fwildcard.c#L1889) is used that is not covered by the tests, but I will merge [the PR](https://github.com/vermaseren/form/pull/519), as it should resolve the issue.

**Comment by jodavies** [comment]
> OK, I'm still unsure how [a certain code path](https://coveralls.io/builds/67610421/source?filename=sources%2Fwildcard.c#L1889) is used that is not covered by the tests, but I will merge [the PR](https://github.com/vermaseren/form/pull/519), as it should resolve the issue.

I just remembered that MATAD has some weird syntax that I was not aware of, does this hit your code path?
```
Vector p,q;
Tensor T;
Local test = p.q;
Identify p = T(?);
Print +s;
.end
```

**Comment by tueda** [comment]
> I just remembered that MATAD has some weird syntax that I was not aware of, does this hit your code path?

This doesn't seem related to `EATTENSOR`, though it would be interesting to see whether `T(?)` is covered by the current test suite.

**Comment by jodavies** [comment]
> > I just remembered that MATAD has some weird syntax that I was not aware of, does this hit your code path?
> 
> This doesn't seem related to `EATTENSOR`, though it would be interesting to see whether `T(?)` is covered by the current test suite.

Right, and it is already there actually: `Issue125_{1,2}`.
