### ISSUE TITLE
macOS-11 runner deprecation

### ISSUE THREAD

**Issue by jodavies** [vermaseren/form#536]
According to https://github.blog/changelog/2024-05-20-actions-upcoming-changes-to-github-hosted-macos-runners/ the macOS-11 image the CI is using will soon be deprecated.

This can be moved to macOS-13 for an Intel based test, but maybe it is interesting to also add macOS-latest for an M1-based test? This could also run the actual tests rather than testing build only?

**Comment by tueda** [comment]
Using the `macos-14` image in the `deploy` workflow should be easy, but the current status of the image may not be comfortable: https://github.com/actions/runner-images/issues/9638. Some workaround is needed.
