### ISSUE TITLE
Speeding up the insertion of reduction tables using tablebases

### ISSUE THREAD

**Issue by vsht** [vermaseren/form#556]
Hi,

I'm sure that people have already run into similar issues in the past, so hopefully there should be a solution to my problem.

Upon doing an IBP reduction I end up with quite complicated tables that I want to insert using FORM. To speed things up
as much as possible, I first generate fill statements, then create tablebases out of them and finally apply those to my 
expression.

In the case at hand there's only one single integral but a very complicated reduction rule.

```
S lsclEp, u0b;
CF topology5534, lsclNum, lsclDen, lsclEpHelpFlag;

L exp = topology5534(1,1,1,1,1,1,1,1,1,1,1,-1)*lsclEp;

.sort 

TableBase "tablebaseExpanded0.tbl" open;
TableBase "tablebaseExpanded0.tbl" enter;

 .sort: TableBase;
 
id topology5534(?a) = tabIBPtopology5534(?a);

 testuse tabIBPtopology5534;

.sort: TestUse;

* print;

apply;

.sort: Apply;

.end
```

The corresponding tablebase and the fill statements used to generate it are attached.

[tablebase.zip](https://github.com/user-attachments/files/16964452/tablebase.zip)

Here's the code I use for generating tablebases

```
off statistics;

S lsclEp, u0b;
CF topology5534, lsclNum, lsclDen, lsclEpHelpFlag;


#include fillStatementsExpanded0.frm #lsclCurrentTopologyDefinitions

CF 
#include fillStatementsExpanded0.frm #lsclTopologyNames
;


Table,sparse,zerofill,strict,tabIBPtopology5534(`LSCLCURRENTNPROPS');


#include fillStatementsExpanded0.frm #lsclFillStatements
.sort 

TableBase "tablebaseExpanded0-new.tbl" create;
TableBase "tablebaseExpanded0-new.tbl" addto tabIBPtopology5534;


.sort

.end
```

My problem is that .sort after `apply;` literally takes ages (currently running on a cluster for over 6 days!) and requires a lot of
RAM. 

So any trick to speed up this insertion would be highly appreciated.

Cheers,
Vlad

**Comment by jodavies** [comment]
It will help if you can prepare your Fill statements without any factorization. Brackets are not expanded in the Fill statement's RHS, so those are being expanded only when the tablebase is applied.
