### ISSUE TITLE
question about div_

### ISSUE THREAD

**Issue by jmbrod** [vermaseren/form#559]
Hello,

why does

```
s x;
l exp = div_(1,x) ;
print;
.end
```
yield `exp = 0;` and not `exp = x^-1;`? (This is what I get, as expected, when I define `l exp = 1/x;` instead.) If I read the documentation correctly, the arguments of `div_` can be any subexpressions. (Maybe I do not understand what subexpressions are?)

Thanks for any help!

**Comment by tueda** [comment]
This is because $1 = 0 \times x + 1$ in the sense of polynomial division (the quotient is $0$). The reference manual says

> div_(x1,x2) is replaced by the quotient of the arguments. 

For reference, the Mathematica counterpart (for univariate polynomials) is `PolynomialQuotient[1, x, x]`, which gives `0`.

**Comment by jmbrod** [comment]
OK, I see, thank you! (I should have read more carefully.)
