### ISSUE TITLE
macOS 12 runner deprecation

### ISSUE THREAD

**Issue by tueda** [vermaseren/form#560]
We have resolved #536, but now unfortunately the `macos-12` runner image is deprecated and will be unsupported by 3 December 2024 in GitHub Actions.

See also: https://github.com/actions/runner-images/issues/10721

**Comment by jodavies** [comment]
It looks like things run through fine if we swap 12 for 13, so this should be straightforward.

**Comment by tueda** [comment]
Well, I am not sure if the binary built on a newer macOS will run on older versions. And macOS 13 image will likely be deprecated one year later, but it is the last x64_64 runner image (unless on a paid plan). No one uses Intel Macs at that point??

**Comment by jodavies** [comment]
Maybe, "how many people actually use the pre-compiled binaries" is something we should have discussed at the workshop. Without the runners there is not really any choice regardless, if binaries should be provided via github. Keeping macos-13 is probably good if it is the last x86-64 macos runner, even if it indeed has to be removed in a year's time.

**Comment by jodavies** [comment]
Looks like we need to make this change now, the CI doesn't run on the macos-12 runners as of today.
