### ISSUE TITLE
count_()

### ISSUE THREAD

**Issue by veretin** [vermaseren/form#566]
Hello!
The following does not work:

s x,y,z;
c A;

g f = 1 + x + 3*x^2 + x*y;
multiply A(count_(x,1));

print;
.end

Best wishes,
Oleg Veretin

**Comment by jodavies** [comment]
Inside `A` the count is zero when `count_` is replaced.

You can do this with
```
Identify x^z? = x^z * A(z);
```
but if you need to use `count_` to do more complicated things, you can also use a dollar variable:
```
s x,y,z;
c A;

g f = 1 + x + 3*x^2 + x*y;

$tmp = count_(x,1);
multiply A($tmp);

print;
moduleoption,local $tmp;
.end
```

**Comment by veretin** [comment]
Hi, thank you for the replay. Yes, I actually want to make more complicated counting and it was reasonable to assume that
A(count_(x,1)) would count powers of x in the term. But variant with $tmp works!

**Comment by vermaseren** [comment]
Actually it does count in the current term, but the term it counts it in, is in the argument of A. Arguments are little subexpressions with terms. In that sense it is consistent, but as Josh pointed out, the $tmp works fine because at that moment the current term is the one you intended.

**Comment by veretin** [comment]
What would mean the following?

multiply z^count_(x,1);

**Comment by vermaseren** [comment]
In this case the internal power function is invoked. That one has two arguments: exp_(z,count_(x,1)) and hence the count_(x,1) would become zero as you can see in this little program:

S   x,z;
L F = x^4;
Multiply z^count_(x,1);
Print;
.end

  F = x^4;
