### ISSUE TITLE
Vector in polyratfun vanishes

### ISSUE THREAD

**Issue by jodavies** [vermaseren/form#567]
In trying to compare OPITeR to other tensor reduction routines I hit the following (due to an autodeclare, I did not notice that `q22` was taken as a vector):

```
#-

Vector q22;
*Symbol q22;

Vector q2;
Symbol D;
CFunction rat;
PolyRatFun rat;

Local test = q2.q2*rat(-1,D - 2);

Identify q2.q2 = rat(q22,1);

Print +s;
.end
```
produces
```
test =
    + rat(0,1)
   ;
```
which then vanishes after another sort.

Putting a scalar product into rat of course crashes like
```
ERROR: polynomials and polyratfuns must contain symbols only
```

This goes at least as far back as FORM 4.1, it is a bit surprising that no one encountered this before.

**Comment by tueda** [comment]
Indeed, `v4.0-20120330` and `v4.0-20120410` give the same result, `+ rat(0,1)`.

**Comment by tueda** [comment]
Arguments of the ratfun should be checked and the error should occur for these cases:
```form
CF rat;

F f;  * including (C/N)Functions, (C/N)Tensors, (C/N)Tables.
V v;
I i;

PolyRatFun rat;

L F1 = rat(f,1);
L F2 = rat(v,1);
L F3 = rat(i,1);

P;
.end
```

**Comment by jodavies** [comment]
The bad test is this one:
https://github.com/vermaseren/form/blob/61ecfdd9655bae0641e6a3a01ae73edfd1a081b9/sources/poly.cc#L2413

**Comment by jodavies** [comment]
The problem relates to fast notation. `rat(2*f,1)` etc already causes termination. The fast notation causes the "non-fast" loop to not run, and simply produces a numerator of 0. The above should fix things I think.
