### ISSUE TITLE
Transform decode

### ISSUE THREAD

**Issue by jodavies** [vermaseren/form#575]
As I understand the manual, the following should print the input expression again, but I can't seem to get "decode" to do anything.

```
CFunction f;

Local test = f(1,0,1,0,1);

Transform f encode(1,last):base=2;
Transform f decode(1,last):base=2;

Print +s;
.end
```

**Comment by tueda** [comment]
You need 5 bits to decode 21:
```form
Transform f decode(1,5):base=2;
```

**Comment by jodavies** [comment]
OK, now I see what it means. How useful is this really, if you don't know apriori what the arguments are?

**Comment by vermaseren** [comment]
Usually you know from the encode. It is a great savings when you have to manipulate/sort/process a very large number of very small arguments. You store then temporarily as a single argument and only by the time you need the individual arguments you decode. This made an enormous difference when manipulating MZV’s and constructing the MZV datamine.
If you do not know how many arguments there might come, you can specify a number that is too big, and you get leading zeroes. You can strip those if necessary.

**Comment by jodavies** [comment]
OK thanks, I will add a test case for it.

Also ZtoH and HtoZ are not currently in the documentation.

**Comment by vermaseren** [comment]
Maybe one could add a feature to Transform: strip leading zeroes.
Not that one can then specify (1,10000) or something silly like that, but a small overestimate is then not a disaster while at the same time not needing a statement like
Repeat id f(0,?a) = f(?a);
which would be much more expensive.
