### ISSUE TITLE
.sort or .sort\n .sort

### ISSUE THREAD

**Issue by veretin** [vermaseren/form#577]
Guten Morgen!

The following code:

```
g ff = 1;
.sort

#if ( isnumerical(ff) )
  #message HERE!
#endif
.sort

print;
.end
```

Here we have no effect of #if.  If I put another .sort, then it works.

**Comment by tueda** [comment]
Thanks for the bug report!

I can reproduce it, but

> If I put another .sort, then it works.

I'm not able to reproduce that fix. Where did you put another `.sort` to make it work?

**Comment by tueda** [comment]
For some reason,

https://github.com/vermaseren/form/blob/bc0dae9ca6d470d308ca2c99ab5b8a269566686a/sources/pre.c#L4865

doesn't fill anything (`*term == 0`), even though a term is clearly present, with

https://github.com/vermaseren/form/blob/bc0dae9ca6d470d308ca2c99ab5b8a269566686a/sources/pre.c#L4861

returning `1`.

**Comment by veretin** [comment]
Hi!

I put two sorts together

```
.sort
.sort
```

**Comment by tueda** [comment]
> I put two sorts together

Hmm... I cannot reproduce it in my environment.

**Comment by veretin** [comment]
I noticed the following:
If I run TFORM without options the code below (with 2 sorts) doesnot give message,
but if run e.g. with -w32 option it works.


````
g ff = 1;
.sort
.sort

#if ( isnumerical(ff) )
  #message HERE!
#endif
.sort

print;
.end
```

**Comment by jodavies** [comment]
Right, I can reproduce what you see. The problem in `store.c` `GetOneTerm`:
https://github.com/vermaseren/form/blob/15c9d7f00714ddc224c0c23c0efa5f79573fab6b/sources/store.c#L1379-L1381
In the non-working case, `POfill` is `PObuffer` in `execute.c` `GetFirstTerm`.

**Comment by jodavies** [comment]
Right, as far as I can tell the pre-proc instruction is processed before that module's call of `RevertScratch`. So when it fetches a term, it is looking in the previous module's buffers. But I don't yet understand why the "double-sort" solution doesn't work in regular form.

**Comment by jodavies** [comment]
I think this should fix things in your case: https://github.com/jodavies/form/tree/issue-577

But it is not quite the whole story for `firstterm_`: the (commented) check of "test5" in the added test, does not work in `tform`. By default `tform` should fully process "test4" here, before starting on test5, so I am yet sure why it does not find "test4" in the outfile.
