### ISSUE TITLE
Feature request: access to termsin() and related functions outside of #if

### ISSUE THREAD

**Issue by magv** [vermaseren/form#589]
Hi, all. Since there's a lot of activity here, I was thinking that maybe a feature request might succeed. So, the `#if` statement has access to a few functions that provide information about expressions, i.e. `termsin()`, `isnumerical()`, and a few others. There doesn't seem to be a way to export this information though: there's no way to e.g. `#write <file> "%s", termsin(myexpr)`. Would it be possible to make this information available outside of `#if` statements somehow? Or, if there's already a way, please tell me.

From issue 585 I've learned that `ZERO_myexpr` can be used as a preprocessor variable to check if `termsin(myexpr)` is 0. So maybe this can be extended to provide `TERMSIN_myexpr` too. Alternatively, if `termsin(myexpr)` would become a recognized preprocessor expression, this would also work. The exact syntax does not matter to me, as long as I have access to the information.

Thanks in advance.

**Comment by jodavies** [comment]
Hi Vitaly,

There is `termsin_` which you can assign to a (preprocessor) dollar var:
```
Symbol x;
Local test = (1+x)^10;
.sort

#$count = termsin_(test);
#message terms: `$count'
#write <stats> "terms: `$count'"
.end
```
Does this suffice?

**Comment by magv** [comment]
Ooh, I knew posting here would be useful. Thanks a lot, Josh. This indeed works. I guess there's a tiny bit of overhead because of the dollar variable, but that's not important.

There's no `isnumerical_`, right? I don't particularly need it, just asking.

**Comment by jodavies** [comment]
No, but there is (undocumented) `sizeof_` which gives the size of the expression or dollar var in its argument, in units of `sizeof(WORD)`.
