### ISSUE TITLE
Trace4 and Schouten's identity

### ISSUE THREAD

**Issue by vsht** [vermaseren/form#65]
trace4 and Schouten's identity

It has been stated multiple times that all the trace algorithms that FORM uses are public and described in the manual. However, there seems to be one trick that FORM uses a lot and which is not mentioned anywhere. 

What I mean is the ability of FORM to generate shorter expressions for  4-dimensional traces, as compared to what one would normally get by blindly applying the  formulas. The shorter expressions are of course correct by the virtue of the Schouten's identity, but FORM is obviously not using this identity directly to obtain the more elegant results.

Let us consider for example the trace of 10 gamma matrices and one gamma 5, where all the matrices have different indices.
```

I       m1,m2,m3,m4,m5,m6,m7,m8,m9,m10;
.global
L       F = g_(1,m1,m2,m3,m4,m5,m6,m7,m8,m9,m10,5_);
Trace4,1;
Print +f +s;
.sort
.end
```

Here FORM returns 180 terms. However, if one naively applies the identity

```
 g_(1,mu,nu,ro) =
                 g_(1,5_,si)*e_(mu,nu,ro,si)
                +d_(mu,nu)*g_(1,ro)
                -d_(mu,ro)*g_(1,nu)
                +d_(nu,ro)*g_(1,mu)
```
		
starting with the first 3 matrices (m1,m2,m3 etc.) one gets 204 terms. I'm really curious how FORM can almost always avoid the appeareance of the 34 spurious terms that vanish by Schouten? This particular trick doesn't seem to be mentioned neither in the FORM manual, nor in the standard literature (e.g. Gammatrica)...

**Comment by vermaseren** [comment]
It is also a matter of the order of contraction of the Levi Civita tensors.
It seems most natural to contract the ones with the largest number of common indices first.
That is of course also purely 4-dimensional.

Jos

**Comment by vermaseren** [comment]
Now a somewhat more detailed answer.
Take the program
I   m1,...,m20;
L   F = g_(1,m1,...,m10,5_);
repeat;
    id,once,g_(1,m1?,m2?,m3?) = g_(1,5_,m20)*e_(m1,m2,m3,m20)
                +g_(1,m1)*d_(m2,m3)-g_(1,m2)*d_(m1,m3)+g_(1,m3)*d_(m1,m2);
    sum m20;
endrepeat;
Trace4,1;
Contract,0;
Print +f +s;
.end
This will give the 180 terms.
If you leave out the repeat loop, you will get the 204 terms. Why?
When FORM does the trace it only looks at that moment at the trace itself. After doing a single
substitution there is a Levi Civita tensor outside. The trace algorithm does not consider this. The
result is that the contractions of the Levi Civita tensors that are part of the trace algorithms are
not quite optimal. With the replace loop there is nothing to contract for the trace routines and then
the full set of contractions are given to the contract statement. This again attacks it by first doing
pairs with the largest number of common indices, and so on.
By the way: don’t forget the sum statement, or you will end up with lots of m20 indices in the same term.
This is also why you should use id,once.

OK, I hope this helped.

Jos

**Comment by vsht** [comment]
Thank you very much for the detailed answer. Apparently I had some misconception on the proper 
application of the g_(1,mu,nu,ro) identity that now got clarified. Furthermore, I was not aware that one can avoid spurious terms in contractions of multiple Levi-Civita tensors by contracting the pairs with the largest number of common indices first.

One can e.g. nicely see that in

```
e_ (i1, i2, i3, dummy1) e_ (i4, i5, i6, dummy1) e_ (i10, i11, i12, 
  dummy2) e_ (i7, i8, i9, dummy2)
```
where if we contract the first and the second and the third and the fourth pieces first, the result contains only 36 terms. However, by contracting the first with the third and the second with the forth one ends up with 360 terms. 

I really feel enlightened now. Thanks again for you explanation, it was enormously helpful!
Vladyslav.
