### ISSUE TITLE
bracket and functions

### ISSUE THREAD

**Issue by vsht** [vermaseren/form#68]
Hi,

it seems that bracket behaves very different on expressions that contains function as compared to expressions that have only symbols. For example, I thought that to factor different parts of terms into two different functions I could just use bracket and collect twice. 

```
Off s;
AutoDeclare F f;
AutoDeclare V v;
F head1,head2;
S a,b,c,d,e,f;
Local expr = f1(v1,v2)*f1(v2,v3)*f2(v4,v5)*f2(v5,v6);
Local expr2 = 5*a*b*c*d*e*f+ 10*a*c;
.sort
bracket f1,b,c;
.sort
collect head1;
.sort
bracket head1;
.sort
collect head2;
print;
.end
```

For expr2 this works as expected and does exactly what I want. However, in case of expr1 FORM prefers to put just (1) outside of brackets, completely ignoring that there is also f1. Is there a way to to change this behavior?

Cheers,
Vladyslav

**Comment by crmafra** [comment]
On Mon, 28 Mar 2016 at 12:26:02 -0700, Vladyslav Shtabovenko wrote:
> Hi,
> 
> it seems that bracket behaves very different on expressions that
> contains function as compared to expressions that have only symbols.
> For example, I thought that to factor different parts of terms into two
> different functions I could just use bracket and collect twice. 
> 
> ```
> Off s;
> AutoDeclare F f;
> AutoDeclare V v;
> F head1,head2;
> S a,b,c,d,e,f;
> Local expr = f1(v1,v2)*f1(v2,v3)*f2(v4,v5)*f2(v5,v6);
> Local expr2 = 5*a*b*c*d*e*f+ 10*a*c;
> .sort
> bracket f1,b,c;
> .sort
> collect head1;
> .sort
> bracket head1;
> .sort
> collect head2;
> print;
> .end
> ```
> 
> For expr2 this works as expected and does exactly what I want. However,
> in case of expr1 FORM prefers to put just (1) outside of brackets,
> completely ignoring that there is also f1. Is there a way to to change
> this behavior?

If you use a commuting function (CFunction) to declare head1,head2
it seems to work as you want.

**Comment by vermaseren** [comment]
Right!
Just think of what happens with non-commuting functions. The bracket is of course on the right
and hence head1 is to the right of your functions.
Now think about what bracket head1 is supposed to do.

Jos

**Comment by vsht** [comment]
@crmafra 
Thanks, this indeed does the trick. I apparently forgot that functions in FORM are non-commuting by default.
@vermaseren 
Thanks, Jos. I now see that that applying bracket on non-commuting functions is tricky, so one has to be careful.
> If the function is non-commuting, all other functions and/or tensors that are non-commuting and
are to the left of the specific function(s) or tensor(s) will also be outside parentheses.

Cheers,
Vladyslav
