### ISSUE TITLE
"Setups: PATHVALUE not yet implemented"

### ISSUE THREAD

**Issue by vsht** [vermaseren/form#72]
Hi,

although setup options `path` and `incdir` are currently not implemented, they are listed in the manual (Ch 16) as if they were ready to be used. I think it would be good to comment out the corresponding lines in the manual.

Cheers,
Vladyslav

**Comment by tueda** [comment]
`path` and `incdir` as setup parameters were implemented in Jos's commit, and now the corresponding test case `features.frm # Issue72` cleanly works. So I close this issue.
