### ISSUE TITLE
"PolyRatFun cannot have zero arguments" when used in function

### ISSUE THREAD

**Issue by benruijl** [vermaseren/form#73]
The following program crashes with the error: PolyRatFun cannot have zero arguments.

	S ep;
	CF rat,K;
	PolyRatfun rat;

	L F =  K(rat(ep+1,1)) + K(rat(1,1));

	.end

**Comment by vermaseren** [comment]
Unfortunately the polyratfun does not work inside function arguments.
It works only at the ‘ground level’.
Of course, it is not to create error messages either.

Jos

**Comment by benruijl** [comment]
For my use case, it is not necessary that the polyratfun does its magic
inside a function. If it is just treated as a regular function, that's good
enough.

Op zo 3 apr. 2016 20:28 schreef Jos Vermaseren <notifications@github.com>:

> Unfortunately the polyratfun does not work inside function arguments.
> It works only at the ‘ground level’.
> Of course, it is not to create error messages either.
>
> Jos
>

**Comment by vermaseren** [comment]
Repaired
