### ISSUE TITLE
Minus sign is ignored in set restriction

### ISSUE THREAD

**Issue by benruijl** [vermaseren/form#78]
The following program returns 1, whereas actually it shouldn't match:

	V p,p1;
	CF vx;

	L F = vx(-p1);
	id vx(p?!{p1,-p1}) = 1;
	Print +s;
	.end

If minus signs are not allowed in sets (although they would be handy!), the compiler should give an error.

**Comment by vermaseren** [comment]
Hi

Vector sets can only consist of vectors like p, not -p.
At the moment it is not quite clear how that could be implemented.

Jos

**Comment by benruijl** [comment]
The latest version fails to match with the minus sign if it is not the first element in the set:

	#-
	V Q;
	CF vx;

	L F = vx(-Q);
	id vx(Q?{Q,-Q},?a) = vx(?a); * {-Q,Q} does work

	Print +s;
	.end

**Comment by vermaseren** [comment]
Ja, ik heb ook nog wat van dat soort probleempjes.
Gaat aan gewerkt worden.

Jos

**Comment by tueda** [comment]
Fixed in c5a24b7c2b476a3c3a65f524d4b14ed4bf3a7059.
