### ISSUE TITLE
Minus sign matching bug in latest version

### ISSUE THREAD

**Issue by benruijl** [vermaseren/form#82]
The following program does not match:

	#-
	V p1,p2;
	CF vx;

	L F = vx(-p2);
	id vx(p2?!{p1}) = 1;

	Print +s;
	.end

**Comment by vermaseren** [comment]
Hi Ben,

In my version it runs fine.

Jos

**Comment by benruijl** [comment]
Fixed in e4de6b28f190ec00470121913f86a8c153e856be.
