### ISSUE TITLE
Erroneous matches on complicated pattern

### ISSUE THREAD

**Issue by benruijl** [vermaseren/form#83]
The following program causes an infinite loop, since the pattern keeps matching. In fact, in shouldn't match at all:

	#-
	S n1,...,n20;
	V Q,p,p1,...,p20;
	CF vx,vy,vxc,vz;

	L F = vz(1,Q,p1,p2,p3)*vxc(1,Q,p1,p2,p3)*vy(1,-p1)*vx(1,-p1)*vx(0,p1)*vxc(0,Q,p1,p2,p3);

	repeat id vz(n1?,?a)*vxc(n2?,?a)*vy(n1?,?b,-p?,?c)*vx(n2?,?d,p?,?e) = vz(n1,?a)*vxc(n2,?a)*vy(n1,?b,p,?c)*vx(n2,?d,p,?e);

	Print +s;
	.end

Simpler programs do seem to work.

**Comment by tueda** [comment]
I think a simplified program (by removing irrelevant complicated arguments) of your example is
```
S n1,n2;
V p,p1,p2;
CF vxc,vy,vx;

L F = vxc(0)*vxc(1)*vy(1,-p1)*vx(1,-p1)*vx(0,p1);

#do i=0,10
  id vxc(n2?)*vy(n1?,-p?)*vx(n2?,p?) = vxc(n2)*vy(n1,p)*vx(n2,p);
  P "%t";
#enddo

.end

```
which still enters to an infinite loop, but it's working correctly...

**Comment by benruijl** [comment]
Why is this correct behaviour? It is matching p to -p1 and to p1 at the same time.

**Comment by benruijl** [comment]
Well, that's not a correct simplification, since this condition vz(n1?,?a)*vxc(n2?,?a) is not there anymore. That one should make sure that n2 is 1.

**Comment by tueda** [comment]
In your example, all `vz` and `vxc` functions contain `Q,p1,p2,p3` in their arguments, so always `?a = Q,p1,p2,p3` and `vxc(n2?,?a)*vx(n2?,?d,p?,?e)` can match with `vxc(0,Q,p1,p2,p3)*vx(0,p1)` or `vxc(1,Q,p1,p2,p3)*vx(1,-p1)`, right? Then, `p` can matches with both `p1` and `-p1`. So `vz(n1?,?a)*vy(n1?,?b,-p?,?c)` always matches to `vz(1,Q,p1,p2,p3)*vy(1,-p1)` or its alternative `vz(1,Q,p1,p2,p3)*vy(1,p1)` after the replacement.

**Comment by benruijl** [comment]
Ah, you are right. Been staring too long at this!
