### ISSUE TITLE
Set to match with a vector

### ISSUE THREAD

**Issue by tueda** [vermaseren/form#84]
We have sets of `symbol_` and `index_`. It would be nice to have `vector_` as well, which can be used for pattern matchings to a vector (not a vector-like expression). Currently, for example, we need to define a set of all possible momenta, in order to match with `-1 * p1?`:
```
Set allpp,p0,...,p99,Q,P;
CF v;

id v(-p1?allpp) = v(p1);
```

**Comment by vermaseren** [comment]
Hi Takahiro,

Is this what you wanted?
    V   p,p1,p2,p3,p4,p5,p6;
    CF  f,g,h;
    L   F = f(p1,-p1,p2,-p2);
    id,all,f(?a,-p?vector_,?b) = f(?a,p,?b)*g(p);
    Print +f +s;
    .end

   F =
       + f(p1,p1,p2,-p2)*g(p1)
       + f(p1,-p1,p2,p2)*g(p2)
      ;

Jos

**Comment by tueda** [comment]
Yes, that's right. Thanks.

**Comment by tueda** [comment]
Implemented in 78aa53b62a.
