### ISSUE TITLE
Feature request: (anti)bracketing w.r.t. a set

### ISSUE THREAD

**Issue by t-hahn** [vermaseren/form#87]
Would it be possible to add (anti)bracketing with a set?  As in:
s a, b, c, d;
set ab: a, b;
L test = (a + b)*(c + d);
b ab;
print +s;
.end
Ideally (anti)bracket would accept both sets and non-sets (variables).

Best, Thomas

**Comment by vermaseren** [comment]
Under construction. May take some time though.

Jos

**Comment by vermaseren** [comment]
Should work now.
