### ISSUE TITLE
Optimization crashes with trivial expressions.

### ISSUE THREAD

**Issue by johannfelixsoden** [vermaseren/form#9]
After commit 59aca1518bcc49da186e09bb41547c38cb40cd42, the optimization fails with very trivial expressions like:

```
Local expr=1;
.sort
Format O2;
#Optimize expr;
.end
```

Error message:

```
test.frm Line 5 ==> Illegal empty value for preprocessor variable optimscheme_
```

The current git master and the "4.1" FORM binaries (build date Jan 13 2014) supplied on the FORM website are affected, but not the [4.1 release on github](https://github.com/vermaseren/form/releases/tag/v4.1-20131025).

As we are using FORM in an automated environment, it would make additional effort to catch trivial expressions.

**Comment by tueda** [comment]
FYI: This was a completely different bug from #7. As of November 2018, it has been fixed, while #7 still remains and leads to a crash.

It was introduced by 59aca15 and resolved by 84d7188.
