### ISSUE TITLE
Errors in symbol powers

### ISSUE THREAD

**Issue by jodavies** [vermaseren/form#90]
I saw this issue in the forum, and it seems to be related to a (partially) fixed issue I reported a while ago. In particular, the appearance of pi_ is similar to my old problem ( https://www.nikhef.nl/~form/forum/viewtopic.php?f=8&t=132 ).

```
CFunction SP;
Symbol nn, shat;
Vector k1,k2,k3;

Local testExpr0 = shat^(-1+nn);
Local testExpr1 = shat^(-3+nn);
Local testExpr4 = SP(k2,k3)*(shat)^(-3+nn);

Argument;
	Identify nn = 2;
EndArgument;

Print +s;
.end
```
gives
```
   testExpr0 =
       + 1
      ;

   testExpr1 =
       + 1
      ;

   testExpr4 =
       + pi_^-1
      ;
```

and, from my older issue, although the pi_ is fixed, including the sum causes a crash iff there is a - sign in the exponent of the symbol
```
#-
Off Statistics;

Symbol i,x,y,n;

Local test1 = 5^(n) * sum_(i,1,n, x^i);
Multiply replace_(n,3);
Print +s test1;
.sort

Local test2 = 5^(-n);
Multiply replace_(n,3);
Print +s test2;
.sort

Local test3 = 5^(-n) * sum_(i,1,n, x^i);
Multiply replace_(n,3);
Print +s test3;
.end
```
gives
```
   test1 =
       + 125*x
       + 125*x^2
       + 125*x^3
      ;


   test2 =
       + 1/125
      ;


   19  20  11  1  4294967280  5  6  1  4  3  1  4294967293  1  4  21  1  1  1
     3
Called from Generator
Called from DoSumF1
Program terminating in thread 4 at test2.frm Line 18 --> 
```

Thanks,
Josh.

**Comment by vermaseren** [comment]
It is being worked at, but it is not easy to fix it properly.
I have your examples running properly, but I can immediately construct examples on which
it will fail again. Hence it needs some extra work. This exponent stuff is a bit nasty.

Jos

**Comment by vermaseren** [comment]
Has been repaired.
